### ISSUE TITLE
material design

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#432]
```
I was just wondering if we're going to see material design for this app anytime 
soon.....


```

Original issue reported on code.google.com by `roamingp...@gmail.com` on 27 Feb 2015 at 3:33

**Comment by pineapplesan** [comment]
It seems like you attempted at making a material design look, but failed at it. I'm no designer either, but, it would be much better if you reverted to the theme before your last update. Or at least give UA the option to be able to select that old theme. You just replaced the main theme with a half baked attempt at material design. 
The previous theme had some code in it that allowed the phones theme to theme the aedict app as well. 
If you need to see what a Japanese dictionary should look like with material design, look at aoba on the play store. 

But please give us the old theme back until your able to get a gift functional material design theme. 
I used to use your app ALL the time, but unfortunately I can't stand looking at it now. 
Sorry to have you say that.. And so I don't use it as much...

**Comment by mvysny** [comment]
Sorry to hear that, can you please post screenshots with what's wrong with them? I have looked at aoba but it's pink and white only, I don't know how that's any better than Aedict, but yeah I'm no designer (and I have no money left to hire a pro designer on an app that costs $5, sorry).

**Comment by pineapplesan** [comment]
It's not the color that's the problem. There color is pretty good. 
1) you're previous version was good. I don't know if it was intentional, but the phone's theme was able to theme the dictionary too. I think that should be set as an option no matter what. So have at least 3 openings. 
2) ui is important. Not sure what you think of windows 8 but many people don't like the ui, so they didn't use it. I used to enjoy the experience on the aedict app. I would explore words and just pay around and have fun. Now I just use or when I have to. 
3) as for aoba, it's not there color that makes it better in tearms of design. It's the use of the concepts of material design. I'm not a pro designer, but Im good enough to be able to recognize good design. Anyway, aoba does let you pick different colors. 
4) it's it not possible you start off by updating the graphics libraries from there older android ones to the latest one? 
5) your app had curved edges around each category. For example, if you look up genki, there will be one big around genki, another under the definition and another for example each box has curved edges. That's the first thing that needs to go. Each box also has a very outline. I think that needs to go too. Again, I'm not a pro to know what material design needs to have. All I can tell that you're didn't have it yet. 
6) I personally think that there gear icon that you press to get more options for the dictionary, needs to pop out or be removed and places inside the menu button on there very right end. The curved outline is also present when you open that gear. 

I'm post some screen shots when I get a chance. 
Maybe I'll post side by side scream shots of this and aoba, though I don't have aoba. I'll just use the idea from the play store and compare than with ones I take.

**Comment by pineapplesan** [comment]
This app is free and it's not there best, but it's really good in terms of design. Ius a chinese dictionary. It's bout as complex as your so the you can't look to see how they do everything you need since they don't have everything your app has. 
Bit the material design elements are there...
Of you search that play store for material design dictionary, you'll get a few apps you can look at for ideas...

**Comment by mvysny** [comment]
It's hard to both have the Material design and keep the app compatible with older phones. Google provides so-called compatibility library which is unfortunately buggy as hell after last
upgrade it took me month to iron out incompatibilities on random phones.
So, right now I'm very happy that Aedict3 is finally stable and works
for all users, and I'm not going to stick-poke the sleeping dogs

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by mvysny** [comment]
Sorry, I'm no designer and I unfortunately have no time to experiment with different UIs. But if you are, please feel free to design the UI as you like, then post the design here so that we can discuss.
