### ISSUE TITLE
Unethical dictionary use

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#446]
```
With any of the new closed-source versions of aedict, kanjidic2 cannot be 
bundled with this application.  If users only download the dictionary files 
themselves, perhaps you can avoid violating copyright law.  But still, it 
strikes me as unethical to close-source a project that largely depends on an 
open-source dictionary database.

This project was open source before, and it was good.  Now it's not, and while 
I understand the developers' desire to make a living, the spirit of sharing has 
been lost.  This is regrettable but easy to fix by reversing the commercial 
maneuver.
```

Original issue reported on code.google.com by `dpe...@gmail.com` on 9 Mar 2015 at 3:07

**Comment by mvysny** [comment]
I will keep Aedict 2 sources available forever. Currently they are at github. Also, Aedict 2 is available at Google Play for free. Also, you can download APK here, at github. Please let me know if this is not enough.

**Comment by dper** [comment]
I suppose that's a reasonable way to go about things, if you really want to keep the new version proprietary.  Keeping the old code easy to find is a nice thing to do.  :-)

You could try what some other developers do: make their programs open source and their APKs available free in F-Droid but charge for the app in the Play Store.  I know OsmAnd does (when last checked, anyhow) this, and probably some other apps are similar.  Whether that is economically viable I don't know.  On the one hand someone else could fork the project and try to steal their thunder, though I don't know if that's a big risk.  On the other hand, the project keeps the open source community involved.  That means more comprehensive bug reports and increased positive publicity.

That's not to say you should or shouldn't do anything.  No doubt you've put more thought into it than I have and can make up your own mind.  :-)  But there are many options, and perhaps the option above is one you hadn't considered.  Just in case, I list it here.

Other than that, there's nothing more to say on this issue, I think.

**Comment by mvysny** [comment]
There is interesting debate over this issue here: http://programmers.stackexchange.com/questions/146463/paid-open-source-app

My fears are summed up in this paragraph:
"For starters, the vast majority of apps, of the million out there, do not sell well, whether open or closed source. So don't expect any app to sell well unless it is a stand-out app and well marketed.

For iOS apps, someone would need to have paid Apple $99/annum for an iOS Developer program enrollment, plus have a Mac, in order to be able to download your open source, build the app, and load it on their device, without buying your app. Not many end users would do this, even if they had the expertise.

However, there is little or nothing to prevent some other developers from doing this, even submitting it to an app store under their own name, perhaps undercutting your price, or adding advertisements to a free app."

I believe that for OsmAnd it's not in a big risk, because the app is used in masses (100,000+ installs). As opposed to Aedict, which is currently being used by 3000 users (and growing slowly). Open-source community is virtually non-existent around Aedict (sorry Diego ;). Actually, when I stopped developing Aedict2, several users discussed to take over and bring it back to life (and start selling it ;), a few mails were sent and this initiative went dead a year after.

In short, I actually considered open-sourcing Aedict3, but I'm afraid to do so, because of possible piracy. I would very much like to actually retire from work and start working on Aedict3 100%, but that's impossible for now as Aedict3 does not pay my bills currently. And piracy would very much trash this dream of mine. Don't worry, I will consider it later, because I am also intrigued on how the sales will be affected and whether the piracy actually occurs or not ;)

I feel that we understand each other positions better by now. I am not going to OSS Aedict3 right now, but I will definitely consider it in the future. I am however positive in supporting the dictionary communities in any way (add UI in Aedict which will encourage users to add fixes and suggestions to dictionaries), please if you have ideas in this field, please let me hear them.

Currently for example there has been an idea that users could create their own synonymic dictionary, which could then be uploaded to a dictionary community, merged, polished, then made public. What do you think?

**Comment by mvysny** [comment]
Closing as not active, please reopen if necessary.
