### ISSUE TITLE
Invisible icons in ActionBar during selection when in action mode

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#463]
![screenshot_2015-03-27-12-31-58](https://cloud.githubusercontent.com/assets/254091/6876598/3aced3b2-d4c9-11e4-8a59-857df882d44b.png)

**Comment by mvysny** [comment]
Fixed in Aedict 3.14; for all poor souls bitten by this bug in appcompat v7 22.0.0, here is a solution:

                    final View actionContextBar = getActivity().findViewById(R.id.action_context_bar);
                    actionContextBar.setBackgroundColor(0xFF111111);

**Comment by mikemorr** [comment]
This is fixed in the dictionary list in 3.14, thanks! I am seeing a similar issue (blank white bar at the top) if I long-press on the search-field text (as if to copy/paste); screenshot attached.
![screenshot_2015-03-30-13-05-16](https://cloud.githubusercontent.com/assets/2184268/6901806/c50f2408-d6dd-11e4-95d7-899e7ef4af56.png)

**Comment by mvysny** [comment]
Thanks for letting me know, fixed ;)
