### ISSUE TITLE
Vector SODs not displayed on some phones

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#465]
![_20150328_200340](https://cloud.githubusercontent.com/assets/254091/6884792/15960996-d602-11e4-8dfe-8cd2eb694797.png)

**Comment by mvysny** [comment]
I have no idea why this particular phone brand reject to draw vector images. I will add a fallback Settings option to enable the good old raster images.

**Comment by bchino** [comment]
Same problem with my phone and the kanji draw practice I just bought does not work. Is there any solution?
Thank you
bruce.chino@yahoo, fr

**Comment by mvysny** [comment]
I will release a fix version of Aedict tomorrow. Regarding the kanji draw practice: can you please attach the screenshot?

**Comment by mvysny** [comment]
This happens on Android 4.2‎.1 according to user, trying now in the emulator.

**Comment by mvysny** [comment]
Can't reproduce in the emulator. Found a new bug: Android 4.2.2 in Emulator ignores round stroke caps, but I'm too tired of workarounds for this fucking fragmented bullshit named Andro-fucking-sucks.

**Comment by mvysny** [comment]
Okay, I simulated the bug on the Android 4.1.2 emulator, trying to fix now.

**Comment by mvysny** [comment]
Okay, *probably* fixed. As per http://stackoverflow.com/questions/14672482/not-rendering-a-transformed-path instead of Path.transform(Matrix, null), one needs to use new Path().addPath(path, Matrix). Oh great. This is a bug I couldn't foresee, and it renders KanjiDraw absolutely useless to all users of Android 4.1 and 4.2. How many other bugs are still lurking on those 4000 devices I cannot test on? I am so disappointed in Android.

**Comment by bchino** [comment]
Hi Martin,
The bug is fixed on KanjiDraw Practice after installing the APK. I can have the stroke orderon the screen, fixed and dynamic. But, surprisingly, not in the aedic dictionnary.
Thank you for all your work.
Best regards Bruce CHINO
bruce.chino@yahoo.fr
      De : Martin Vysny <notifications@github.com>
 À : mvysny/aedict <aedict@noreply.github.com> 
Cc : bchino <bruce.chino@yahoo.fr> 
 Envoyé le : Dimanche 29 mars 2015 18h13
 Objet : Re: [aedict] Vector SODs not displayed on some phones (#465)
   
Okay, probably fixed. As per http://stackoverflow.com/questions/14672482/not-rendering-a-transformed-path instead of Path.transform(Matrix, null), one needs to use new Path().addPath(path, Matrix). Oh great. This is a bug I couldn't foresee, and it renders KanjiDraw absolutely useless to all users of Android 4.1 and 4.2. How many other bugs are still lurking on those 4000 devices I cannot test on? I am so disappointed in Android.—

**Comment by mvysny** [comment]
Fixed in KanjiDraw 1.3, will fix in Aedict 3.14 soon.

**Comment by bchino** [comment]
Ok, thank you and good luck!
Best regards
Bruce CHINO
bruce.chino@yahoo.fr
      De : Martin Vysny <notifications@github.com>
 À : mvysny/aedict <aedict@noreply.github.com> 
Cc : bchino <bruce.chino@yahoo.fr> 
 Envoyé le : Dimanche 29 mars 2015 23h52
 Objet : Re: [aedict] Vector SODs not displayed on some phones (#465)
   
Fixed in KanjiDraw 1.3, will fix in Aedict 3.14 soon.—

**Comment by mvysny** [comment]
Dear Sir, thank you for your patience. If I were to buy an application which shows a blank screen upon start, I would be furious. I once again apologize, although this is a bug in Android and I have no capacity to test the app on multitude of phones :(

**Comment by mvysny** [comment]
Fixed in Aedict 3.14
