### ISSUE TITLE
Unrelated search result

### ISSUE THREAD

**Issue by siritinga** [mvysny/aedict#471]
Hi.
I'm not sure if there is something wrong here. When I search for "eru" using exact match, I'm getting an unrelated result (doesn't contain eru): 九死. It seems that it is found in the romaji text, because searching for える does not return it. The definition doesn't seem to contain eru.

**Comment by mvysny** [comment]
This is a long-standing bug which perhaps finally deserved to be fixed ;) The problem is that the "eru" term is being searched in all translations of the entry. The 九死 entry in particular has the following definition:

{kanji=[九死], reading=[きゅうし], senses=[[n]{deu=[(f) Situation, die man sehr wahrscheinlich nicht überleben wird (häufig in der Wendung kyūshi ni isshō o eru = dem Tod mit knapper Not entkommen)], eng=[narrowly averting death]}]}

So, as we can see, the "eru" term is present in the german translation, but not in the english translation, which will be confusing to english users which do not have the german translation shown. I need to fix both the dictionary files and the search engine, to search only in user's configured language (with fallback to EN or DE in case of Wadoku).

**Comment by mvysny** [comment]
Fixed; the fix will be available when Aedict 3.16 is released *and* dictionaries newer than 1.May 2015 are used.

**Comment by mvysny** [comment]
Please make sure that you have Aedict 3.16 or newer installed, then head to Settings / Dictionaries / Dictionary Manager and update all dictionaries. I have just today released a new bunch of dictionaries which should now return only relevant results.
Please reopen if the issue is not fixed.
