### ISSUE TITLE
Double entry for 冷 kanji.

### ISSUE THREAD

**Issue by Sindern** [mvysny/aedict#499]
When looking for the 冷 kanji using handwriting recognition i noticed it's in the dictionary twice.   

One gives results normally but the other returns no results.   

Hopefully this is the right place to report this.

**Comment by mvysny** [comment]
Yes, this is the right place, thanks for letting me know ;) I will verify this issue.

**Comment by mvysny** [comment]
Failed to reproduce this issue with the built-in kanji pad. Are you perhaps using the KanjiDraw paid extension?

**Comment by mvysny** [comment]
Yes, reproduced on the KanjiPad paid extension.

**Comment by mvysny** [comment]
Okay, there apparently are two similar characters:
1. 冷 U+51B7 CJK UNIFIED IDEOGRAPH-51B7 cold, cool; lonely
2. 冷 U+F92E CJK COMPATIBILITY IDEOGRAPH F92E cold, cool; lonely

Apparently, the first kanji is present in both Kanjidic and JMDict; second one is absent from both Kanjidic and JMDict. KanjiPad is correct to find both kanjis, perhaps Kanjidic should be updated to contain information about the second kanji. Can you please write to Jim Breen about your finding?
Meanwhile, I will add a notification message to Aedict, which will be shown in case when the kanji is missing from Kanjidic.

**Comment by mvysny** [comment]
Implemented in Aedict 3.19

**Comment by mikemorr** [comment]
On my device, the 2 characters look the same (final stroke is vertical), although the SOD for 51B7 uses a form where the lower part looks like マ.

Since F92E is semantically equivalent and canonically decomposes to 51B7, I wonder whether F92E should just be suppressed from the KanjiPad search results. 

I notice the same behavior occurs with 令 4EE4 and 令 F9A8.
