### ISSUE TITLE
Ability to set priority of dictionaries

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#502]
If I enable the names dictionary in addition to the standard dictionary, then searching for sushi (寿司) leads to the first 3 hits being people's names. I'd like to either have the standard dictionary be hard-coded to have a higher priority than the others, or for there to be some setting where we can set the priority.

**Comment by mvysny** [comment]
During sentence analysis JMDict always has the highest priority, because other dictionaries produced weird results ;)
However, during regular search, I thought that dictionaries enabled by user should have higher priority than JMDict (user enabled the dictionary after all, and he wants to perform search in it). However, you may be right that sometimes it is preferred to search in JMDict first. I will add a search setting for this.

**Comment by timrae** [comment]
I'm not sure, but I would think in general most people are using the other
dictionaries as a supplement to JMDict...? I'd think in general we only
want to see those results when necessary (i.e. when there is no result in
JMDict).

**Comment by timrae** [comment]
At least for my usage case, I've enabled the names dictionary to supplement
JMDICT sentence analysis, and that has kind of screwed up my ordinary
search.

**Comment by mvysny** [comment]
I see. So perhaps I will always set JMDict to go first, and if someone complains, then I will add the setting for the dictionary ordering.

**Comment by timrae** [comment]
Yeah I think that's reasonable. Just to confirm, the priority would be as
follows, right?

Words tagged with (P) in JMDict
Words tagged with (P) in user dicts
Other words in JMDict
Other words in user dicts

**Comment by mvysny** [comment]
Currently the order is as follows (P) user dicts, other user dicts, (P) JMDict, other JMDict. I can reorder the results as you request though, no problem.

**Comment by mvysny** [comment]
Fixed in Aedict 3.19
