### ISSUE TITLE
When searching for kanjis by radical, some of them are not displayed

### ISSUE THREAD

**Issue by haudren** [mvysny/aedict#508]
Hello there,

I was searching for some kanjis yesterday and just noticed that when looking for kanjis by radical, when selecting a radical, not all of them are displayed in the upper section, see the attached screenshot.

![screenshot_2015-05-25-17-31-04](https://cloud.githubusercontent.com/assets/4352562/7794352/82ca6668-0304-11e5-8e46-e29a5906d671.png)

For example, when selecting 金, neither 釓 nor 釔 are shown, although they have their entries in the dictionary. See the screenshot below, I switched to the "Light theme" to see if it affected the issue.

![screenshot_2015-05-25-17-42-10](https://cloud.githubusercontent.com/assets/4352562/7794432/7a92a3b0-0305-11e5-9a0f-af122de4663d.png)

It looks as if all the not-often used kanjis are missing... Do I need to download other dictionaries ?

On a side note, I was looking for 鉢, from 小鉢 (こばち) : when selecting only 金 or only 木, I can't seem to find it, while when selecting  金 and 木, it shows up as first result. I really do not understand this behavior, especially since 金 is listed as the radical of 鉢.

Thanks a lot for the awesome work, otherwise the app is working great !

Edit : Just for clarification, I am using the latest Aedict3 version on Sony Xperia Z1f.

**Comment by mvysny** [comment]
Hi, thanks for letting me know, and thanks for the praise :)
Regarding the missing kanjis: yes, this seems like a font issue (the kanjis are simply not displayed), please see screenshot from my phone for details. This is however weird, because Aedict is using custom JP font on all phones, so it seems that on my phone Android renders the character correctly, yet on your phone it does not, for unknown reasons. You can try to head to Settings / Expert settings and try checking "Do not use Japanese font" to check if the characters will appear. This will however on many phones (perhaps including yours) render the kanjis incorrectly, as their Chinese counterparts (unless you switch your phone language to JP). Or you can try to download another Japanese font (for example from this page: http://www.freejapanesefont.com/ ) to your phone, then configure Aedict to use it (via the Custom Japanese Font setting) - please try out some of those fonts. Also perhaps please try to open this web page on your phone's browser, to check if the characters are displayed correctly.
Regarding the side note: thanks, intriguing, I will look at it.

**Comment by mvysny** [comment]
![device-2015-05-25-114901](https://cloud.githubusercontent.com/assets/254091/7795315/15207bfa-02d4-11e5-8edc-4d4e3c74f2bc.png)

**Comment by haudren** [comment]
Hello,

Using the system font fixed my issue with the display ! There should not be any problem with the system font since this is a Japanese phone.

Please tell me if you need any more info regarding this issue or the other one.

Thanks,
Hervé

**Comment by mvysny** [comment]
Thanks for letting me know, I'm glad that the font issue is resolved.
Regarding the other issue: I limited the search result to 100 kanjis and 鉢 did not make it :-) I have increased the limit to 1000 and the 鉢 kanji is now correctly found.

**Comment by mvysny** [comment]
Fixed in Aedict 3.22
