### ISSUE TITLE
Add 'parts' access button to kanji (enhancement)

### ISSUE THREAD

**Issue by michaeldesu** [mvysny/aedict#518]
When viewing a compound kanji, to see the parts for one of the knji it's a little labourious:

From this tab view (1): Dict | Kanji | Buddies .. 

tap on the kanji itself to change the view to (2): 

Kanji | Radical | Parts ..

then tap "Parts" to see the parts

It would be nice if there was a parts button near the kanji (or a context menu) when the compound kanji is seen at the view (1) above. In this way, the user can go directly to the parts tab without tapping the kanji again.

**Comment by mvysny** [comment]
Hi Michael, thanks for the bug report. The navigation is always a sensitive topic, because it is hard to get it right. Too many paths to the same information, and the user starts feeling lost. Too many buttons, and the UI will feel over-crammed, especially on devices with small screen real estate, like cell phones. Aedict already contains tons of functionality and navigation paths, and paths with two touches are the shortest amongst them ;)
So, I am sorry but I feel reluctant to add new button, just to reduce two touches into one.
Perhaps this hint will help: you actually do not have to touch the "Parts" tab - you can simply slide the screen with your finger vertically, anywhere, to switch to another tab. Please let me know if this helps.
Closing as won't fix, please reopen if needed.
