### ISSUE TITLE
Floating dictionary window [suggested feature]

### ISSUE THREAD

**Issue by diogovk** [mvysny/aedict#519]
It is often to me, that the words I'm looking up in the dictionary come from another Android app.
This means that for each time I want to look up I have to go the the task switcher, switch to aedict, look up the word, then task switcher again, and then switch to the first app again.
The task switcher in itself is a bit cumbersome, and the whole task switching-and-back in my phone takes a few seconds.
It would be really great if I had a way to have an aedict floating window (similar to https://play.google.com/store/apps/details?id=nqr.multiscreen) with android, which would allow me going instantly from any app to aedict and back.

Not only it would save me time, as it would improve the experience, since I won't feel like I'm being interrupted every couple of minutes.

**Comment by mvysny** [comment]
Thanks for the bug report. Unfortunately, Android does not support such window mode natively - only some Samsung devices support those (it's called a multi-window mode and Aedict3 supports it). Please see video here: http://www.androidcentral.com/using-multi-window-samsung-galaxy-s4
Even the author of Multiscreen Multitasking Phone admits this upfront: "This doesn't run any app in a window unfortunately - that's not possible due to the way Android is programmed - but it is the closest alternative. I've made a unique browser, notepad, drawpad, map and more"
The task switcher being cumbersome is really a bug in Android ;)
However, there is a way to draw on top of other apps. So, perhaps, I can introduce a special app, which, upon clicking on a persistent notification icon, would occupy only a portion of screen, allowing you to quickly lookup a word. However, this approach may not be feasible as I have read on the internet that this approach has several issue with the virtual (software) keyboard not appearing. So, you would not be able to enter any text, which defeats the purpose of such app.
So, perhaps there are three possible solutions:
1. Enable the 'always available' Setting, which will show a permanent notification icon, making Aedict accessible more easily; OR
2. If the app supports text sharing (and browsers usually support this), just select a portion of text and 'share' it to Aedict); OR
3. please watch this video: https://www.youtube.com/watch?v=IuOGewFJ8x0

Please let me know if any of these three options solve your problem.

**Comment by mvysny** [comment]
Regarding the keyboard not being shown: http://stackoverflow.com/questions/10266959/having-application-running-above-other-app "I have only one problem. I want to create an floating EditText, but when you click it, it doesn't show the keyboard..."

**Comment by mvysny** [comment]
Are you perhaps reading a long text, and, from time to time, you only need to click a word to get it translated? Perhaps I can create an app for that, 'Aedict Reader' or something - a simple text reader or web page browser, which, upon touching a word, will get it translated. What do you think?

**Comment by mvysny** [comment]
Something like this? http://cdn.marketplaceimages.windowsphone.com/v8/images/f2918d09-3d5b-4c51-a6d4-fffb9d43098c?imageType=ws_screenshot_large&rotation=0

**Comment by diogovk** [comment]
I'll try enabling the 'always available' option. I forgot about that feature.
I'm pretty sure it will be enough.
In my particular case it is often that I'm reading from "image" files (as opposed to text) so the browser wouldn't help me that much in that case.
The ideal solution would be having the "window" feature directly on Android (not only on those Samsung phones). It doesn't make sense requiring each app to implement that separately.
My phone (LG) actually has some some apps that work as floating windows (browser, calculator), which does help with "multitasking". But that are "special" apps, so aedict is not supported.

**Comment by mvysny** [comment]
If you have image files, perhaps please try Aedict OCR to recognize the characters for you.
