### ISSUE TITLE
Will not Analyze

### ISSUE THREAD

**Issue by boku0801** [mvysny/aedict#522]
大は小を兼ねる.

The above sentence will not analyze, it shows the sentence as written without breaking it apart for analysis...only found this, but there could be others.

Thanks you.

**Comment by mvysny** [comment]
Hi, thanks for letting me know. It is true that this sentence is not broken by Aedict. This is because the sentence appears in the JMDict in its entirety (better too big than too small) and Aedict therefore thinks it is a single word. Perhaps there could be a button, or a menu item, to force Aedict to break this "word" into smaller parts.

**Comment by mvysny** [comment]
Closing as not active, please reopen if necessary.
