### ISSUE TITLE
2.9.4 installed on two devices, can't import notepad backup from one to the other.

### ISSUE THREAD

**Issue by majimekun** [mvysny/aedict#543]
Hi,

As said in the title, the export/import function doesn't work between two different devices with the same version of Aedict installed.

I've hooked the old device (Samsung S4 Zoom) to my PC via USB, copied notepad.backup on my PC, and then, from the PC, copied the file on the new device (Samsung K-Zoom).

On the new device, tapping on "restore" brings the dialog "merge/overwrite" but both merge and overwrite don't produce any result.

Of course I've made sure that notepad.backup isn't an empty file and contains the data I need.

Is there any work around?

Thanks in advance!

**Comment by mvysny** [comment]
Hi Majimekun, thanks for letting me know. If it is okay with you, can you please send me your notepad.backup file to my mail at vysny@baka.sk? I will try the import myself and fix it.

**Comment by majimekun** [comment]
Hi Martin.
I just sent the file by email.
Thank you very very much for that!!!

**Comment by mvysny** [comment]
Hi Majime kun,
  I am very sorry to disappoint you, but I have been unable to find the
bug. The old Aedict's code base is very old and is hard to compile,
because of major advancements in Android development tools (basically
they switched from Eclipse to IDEA, with only a vague notion on how to
maintain backward compatibility. I started to develop Aedict3 from
scratch, so the codebase is completely different). I apologize, but I do
not have any resources left to maintain the old Aedict codebase :( Sorry
man.
Best regards,
Martin

**Comment by majimekun** [comment]
Hi Martin,
Thanks anyway for your effort.
As a solution of last resort, I've tried to open the backup file into LibreOffice Calc but whatever character encoding I tried, there is a great amount of mojibake.
What character encoding did you use?
Is there a way to at least save the backup into a CSV file?

**Comment by mvysny** [comment]
Backup uses Java Serialization which is basically an undecypherable binary blob. You can try to export notepad into a CSV file, but I don't remember if that stuff is even implemented in Aedict 2... Just open the Notepad and search the menu for some Export options.
