### ISSUE TITLE
Export creates too many cards in Anki

### ISSUE THREAD

**Issue by Errol246** [mvysny/aedict#614]
The added functionality of being able to choose which Anki deck to export to is incredibly useful. However, when I export a word to Anki it creates a forward card, a reverse card (which I have manually set up) and a forward card with furigana over the kanji. This third card is totally unnecessary for the learning process and having to cycle through a third card is a waste of valuable study time and I don't want to have to delete a third card for every word I export. There may already be a feature to turn this off but I don't see it, so any instruction as to how to deal with this or a possible fix would be very much appreciated. As long as this problem persists I will have to export the cards to a separate deck and move the correct cards over to my main vocab deck, which isn't ideal.

Thanks for creating the best mobile Japanese dictionary ever. My studies have become 10 times easier because of Aedict3!

**Comment by mvysny** [comment]
Errol, Thank you very much for your praise ;) Actually, Aedict always exports model with three cards for every entry. If you wish to disable the third card, there should be a way to do this in AnkiDroid. I do not use AnkiDroid myself so I am just guessing here. I will try it out myself later;
for the time being please try to edit the Aedict card model (with the ID of sk.baka.aedict3v6) in the AnkiDroid, and disable the relevant card. Please let me know if this helped.

**Comment by Errol246** [comment]
I apologise for the radio silence. My smartphone broke just as I posted, and I haven't gotten a new one until now.

I applied your method. It was as easy scratching my back. Now Aedict3 only synthesises 2 cards, exactly those that I want and need. Done deal. Thank you!

**Comment by mvysny** [comment]
Good, I'm glad that the solution works for you. Closing as won't fix, as the solution is to change the AnkiDroid configuration.

**Comment by denyeo** [comment]
@mvysny I encountered the same problem - I only want to create 1 card instead of Aedict's 3-card model. However, because Aedict created new card types, I can't remove the unwanted card types without causing Anki to do a full sync to AnkiWeb. And a full sync takes ages on my phone and PC because I have multiple very large decks. I want to avoid a full sync, but I can't find a way to suspend creation of new cards of selected card types.

If possible, it would be great if Aedict had a setting allowing me to select which card types to export. Just a simple checkbox list of card types in the Export dialog would do. Preserve the checked/unchecked state. Doing this would give users flexibility on whether to create 1, 2 or 3 cards each time they export to Ankidroid.

Alternatively, if anyone can suggest a way to suspend card types without causing a full sync, please let me know!

**Comment by mvysny** [comment]
@denyeo I am definitely not an expert on Anki, so perhaps @timrae (Tim of AnkiDroid) should join us. Yet, Aedict only creates the Aedict card type once, so perhaps it is possible to edit the Aedict card model (with the ID of sk.baka.aedict3v6) in the AnkiDroid, and disable the relevant card, without causing the dreaded full sync.
Your proposal of creating of the Export dialog is unfortunately probably a no-go: Aedict would have to create all permutations of card types, for all checked/unchecked configurations, which would probably pollute the AnkiDroid card model.
Could you please discuss this issue with https://github.com/timrae first - maybe this is a problem in the full sync of the Anki/AnkiDroid? I will then happily implement any solution you guys deem to be best.

**Comment by timrae** [comment]
@denyeo 
Instead of deleting the unused card templates, you could just configure them so that they would render empty cards, in which case these cards will not be generated. You can do this by deleting all of the code in the front side of the cards that you don't want. You'll need to run the "empty cards" function after doing this to get rid of the unwanted ones that were previous exported from Aedict.

**Comment by denyeo** [comment]
@timrae Great suggestion, thank you very much for coming over to give it! I'll give it a shot.

@mvysny Thank you for being willing to consider my request, and for getting Tim Rae over.

**Comment by timrae** [comment]
:+1:

**Comment by Tch4lla** [comment]
> @denyeo I am definitely not an expert on Anki, so perhaps @timrae (Tim of AnkiDroid) should join us. Yet, Aedict only creates the Aedict card type once, so perhaps it is possible to edit the Aedict card model (with the ID of sk.baka.aedict3v6) in the AnkiDroid, and disable the relevant card, without causing the dreaded full sync.

It's been a while since this issue was brought up, but I'm running into the same problem when it comes to exporting. How do you implement this solution, editing the card model?
