### ISSUE TITLE
Sorting options in the Dictionary Manager 

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#649]
Maybe the Dictionary manager menu could be improved with some sorting options, like sort by status (up to date, updateable, downloadable...). For example I would prefer to have the main dictionaries I use at the top of the list (and even filtering out some of them I will never use).

Additionally different colors or tones could be use for each entry line depending on the dictionary status.

Is there any option to get a notification of new version available when stating the app (or do we need to manually check according to the "auto-check for updates" period value).

**Comment by mvysny** [comment]
Good idea, thank you. As a workaround, you can simply touch the 'update all' button. 
The new dictionary notification should automatically pop once per configured period and only when there are updates. Unfortunately due to the way android works, often the app is not really started,often it is just brought back to the foreground. However, if you are power user and if you tend to kill aedict manually, I can enable the aedict - started check.

**Comment by mvysny** [comment]
Implemented in Aedict 3.39.17. The dictionary list is now by default sorted by status, then by name. You can change the sort order via the upper-right menu.
