### ISSUE TITLE
Synchronisation between devices & aedict-online.eu 

### ISSUE THREAD

**Issue by sugoibachiri** [mvysny/aedict#652]
I am using aedict on several android devices and I also started to use aedict online. i am actively using notepad to save and categories new words. so far i have on each device different notes, which is quite inconvenient. also on aedict-online.eu the list is growing. it would be great,  if there would be a synchronization function similar to anki. i guess it would require some server capacities. may be this is also a next round for for user to support on https://www.patreon.com/aedict?

**Comment by mvysny** [comment]
Thank you very much for your kind support. Actually, the sync support is already implemented both in Aedict Online and Aedict Android, albeit with certain drawbacks. Please read on.

To activate the sync, please fire up your Aedict on your Android phone, head to Settings / User Data / Aedict Online Settings and fill in the username and password. Now, head to Settings / User Data / Backup storage and select "Aedict Online (experimental)". Now, head to Backup and press the upper-right "Backup user data" button - your Notepad, SRS data and Tags will be sent to Aedict Online and merged. To get the data from Aedict Online back to your phone, just touch the "currentdata.zip" entry in the Backup screen - the Notepad, SRS and Tags will be downloaded from Aedict Online and will overwrite the data present on your phone.

Now here's the problem: the merge algorithm is not perfect. It is very simple and is designed so that you will never lose any data; but it has some drawbacks. If you first back up stuff to Aedict Online and then download the "currentdata.zip" entry, you should be safe. However, the category deletion operation performed on your phone is not propagated to Aedict Online and the category will not be deleted at Aedict Online. Only when you delete the category at Aedict Online, the delete operation will be propagated. Please try it out and let me think whether this is okay or whether I should improve this algorithm. 

Improving the sync algorithm is not easy though - eventually when the devices are offline long enough, the conflicts may start to pile up. So, definitely not easy :)

**Comment by mvysny** [comment]
If you wish, you can back up your data locally to your phone before doing any experiments. Just set the Backup storage to "Phone Internal Memory" and perform a backup.

**Comment by mvysny** [comment]
This bug will be fixed when a proper NoSQL database with sync capabilities is used. Depends on #721 and is actually duplicated by it.
