### ISSUE TITLE
Furigana + popup reader

### ISSUE THREAD

**Issue by Rasmusrara** [mvysny/aedict#692]
I just bought a new Japanese ebook and encountered a problem and thought to send you a request/suggestion. The ebook I bought sometimes has furigana above the kanji. Your popup app has been a great help with Japanese ebooks, but my ebooks didn't have furigana until my latest purchase.

What happens when copying a word with furigana looks like this: 肖 しょう 像 ぞう 画 が
So it also copies the furigana and places them in between the kanji. 

I was wondering if there could be some option to include a quick search or a way to edit the copied text in the popup app. Now the fastest way to find a translation for words with furigana is to just simply open Aedict and manually search the word. Google's own Play book translation doesn't come even close to Aedict pop up, but this furigana problem is rather frustrating. The whole purpose of furigana is to make reading easier, now it kind of complicates it :P

**Comment by mvysny** [comment]
Yes, we definitely need to do something about this ;). I'm thinking that perhaps the Reader should auto-detect such cases and simply discard the furigana. A simple but quite reliable algorithm would be to check whether the copied text is in the form of Kanji-Space-Hiragana-Space-Kanji-Space-Hiragana-etc - if yes, it would automatically throw away the hiragana and spaces.

In the abovementioned example, the algorithm would throw away しょう ぞう が along with the spaces around and would simply search for 肖像画.

However, perhaps there are some cases when this is unwanted. I will therefore add a setting option for this, so that this algorithm may be turned off in some (unforeseen) cases.

What do you think?

**Comment by Rasmusrara** [comment]
Sounds like it could easily work. The spaces between each kanji and furigana probably make it easier to do.  Also it's not necessary to copy the last part of a furigana, e.g. with above example 肖 しょう 像 ぞう 画, so this problem doesn't affect one kanji words.

**Comment by mvysny** [comment]
Fixed in Reader 1.3.13. The Reader will now automatically detect furigana and remove it. You can disable this in Reader's Settings - just uncheck the "Auto-Remove Furigana" option

**Comment by Rasmusrara** [comment]
Great update, thanks! :)
