### ISSUE TITLE
Incorrect list of words from Kanji to ON readings in words

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#693]
Try '政' with onyomi 'しょう'

The first word is '郵政省' where the 'しょう' reading indeed is found but for '省' (it is 'せい' for '政').

**Comment by mvysny** [comment]
Hi Andrej, thank you for letting me know. Unfortunately, this is not easily fixed - the JMDict data does not contain readings for separate kanjis in words. Therefore, Aedict can only guess the readings, and in some cases, it will guess incorrectly. However, there perhaps is something I can do, perhaps I can post-process Lucene results to actually verify the reading.

**Comment by mvysny** [comment]
Fixed, the algorithm will now remove obvious misreadings. Yet, without full data on kanji/reading for that particular word, there is unfortunately no way to remove 重商政策: じゅうしょうせいさく... I'm not sure whether I should complicate the algorithm further, by performing a Kanjidic lookup for possible readings... Closing as fixed for now, please reopen if there are any further glaring issues.
Fixed in Aedict 3.39.24
