### ISSUE TITLE
Feature request/enhancement - Add support to display content of Jim Breen tags field, xref, and lsource and dial info

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#717]
I would like to ask for a feature request.

The XML file for Jim Breens Japanese Dictionary file has tag entries to describing the field a particular word comes from and xref (cross reference tags), and Language source tags which indicate which language a word is borrowed from for Japanese loan words, and dialect tags.  But it appears that AEDict does not use this information or display the information in the Dictionary interface.

It would be especially useful to have support for xref, field, lsource and dial fields to narrow down ambiguity.

Here is the xml dtd for those tags which give a better explanation than I am able to.

<!ELEMENT field (#PCDATA)>
	
<!ELEMENT xref (#PCDATA)*>
	
<!ELEMENT lsource (#PCDATA)>
	
<!ATTLIST lsource xml:lang CDATA "eng">
	
<!ATTLIST lsource ls_type CDATA #IMPLIED>
	
<!ATTLIST lsource ls_wasei CDATA #IMPLIED>
	
<!ELEMENT dial (#PCDATA)>

**Comment by mvysny** [comment]
Hi, thanks for letting me know, and I apologize for such a late reply. It is true, I am ignoring several metadata from the data files (including those you pointed out). This is on purpose, to avoid information overload, especially for beginners who just started to learn the language.

However, I may implement this in the same way as with Kanjis - so that you could "pin" the information you need, and that information will then be displayed. This would probably be helpful for advanced learners.

Okay then, I'll add this information, both to the dictionary files and to the Aedict UI.

**Comment by mvysny** [comment]
Implemented in 3.39.29, please make sure that the dictionary files are updated.

**Comment by mvysny** [comment]
Forgot to add xref and field-of-application, reopening.

**Comment by mvysny** [comment]
Ok, added xref and field-of-application. Fixed in Aedict 3.39.29

**Comment by terrywallwork** [comment]
Thanks,

And sorry it took me a while to notice.  I will update dictionaries and give it a run :)

**Comment by mvysny** [comment]
Hold on please, I first need to release new aedict :) you can download the dictionary updates though, but the info will not be displayed until the new aedict is released
