### ISSUE TITLE
Transaction Issue 

### ISSUE THREAD

**Issue by Gonztf** [mvysny/aedict#722]
Hello Developers

 I have bought Aedict Reader Popup however seems that after the purchase the app wasn't registrered on my google account.

On the other hand the Aedict Dict3 that I bought was registrered without any problems and I managed to re-install it.

Could you please fix this issue so im allowed to reinstall the Reader Popup addon? If thats not possible please refund my purchase.

Thanks in advance.

**Comment by mvysny** [comment]
Hi, I'm sorry to hear that. Unfortunately I have no means to control or resolve the installation/registration issue - such issues are resolved by Google guys. The only thing I can do is to provide refund.

Therefore, I recommend you to contact Google first, regarding the installation issue. In case Google will not resolve your issue satisfactory, just please let me know your transaction ID and I will refund, no questions asked. There is no time limit for refund, so there's no rush.

**Comment by Gonztf** [comment]
woow I didn't expected a quick reply!

This info may be helpful to check the transaction:

google ID: knakasone7@gmail.com
App bought on: 04/11/2016

Im suspecting maybe the problem happened because I bought the extension
within the app by using the links provided at the startup of the app. Its
just an assumption though.

thanks in advance.

**Comment by mvysny** [comment]
Hmm, it shouldn't matter how you navigated to the Google Play - the purchase should go through in any way.

I checked my console and there is indeed such transaction for Aedict Reader Popup. The transaction shows in my console as "Canceled", so the money should be eventually returned to you. Since the transaction is canceled, I cannot refund - I assume that the money should be returned to you soon. If not, you will need to contact Google guys, to address this issue.

**Comment by Gonztf** [comment]
Yes I noticed that too, transaction showns as Cancelled.  Is quite strange because im pretty sure I didn't cancelled the purchase, I used the extension for about a month and as far I know is not possible to cancel an app purchase after a long period of time. 
Anyways I'll give a try at contacting google guys as you suggested. 

Thanks for the quick reply and for your time.

**Comment by mvysny** [comment]
Any reply from the Google guys? Were you able to resolve the transaction issue?

**Comment by Gonztf** [comment]
My japanese isn't great at all, I doubt I'll be able to explain the issue to google JP support. Thought on calling the US support but my english listening/speech skills are very poor (and the call expense could end quite expensive too). 

I seached a bit about this issue and tried several solutions without luck.

I don't know if this unwanted "cancelled" transaction refunded my money. If the money spent was refunded after the unwanted cancellation, with no-doubt I would re-purchase the extension since I found it quite useful. 

If you couldn't find any reason about this problem Im fine about the thread being closed.

**Comment by mvysny** [comment]
True, I understand you. I once called the US support and couldn't understand a single word, because of low sound quality (I called from Slovakia). I asked Google to provide an English-speaking e-mail support, but I assume that's not going to happen anytime soon.

But, you can try to select your mother tongue at this page, so at least you can phone to somebody speaking your mother tongue: https://support.google.com/googleplay/answer/6179357

Unfortunately I cannot provide the refund as the transaction shows "Canceled". In such case the money should be returned to you, but unfortunately I cannot help this process in any way (besides bombarding Google with phone calls :-). So, with your permission I'm marking this issue as closed.
