### ISSUE TITLE
Sort kanji junctures - Enhancement

### ISSUE THREAD

**Issue by Teomada** [mvysny/aedict#724]
Hi,
Kanji junctures seem to be listed without a specific sorting criteria. It would be good to order them by increasing level of difficulty, e.g. by JLPT level. If the list of available junctures is very long, typical for fundamental kanjis, it might affect responsiveness of the app, so ideally an option to enable/disable this function should be available.
Thanx

**Comment by mvysny** [comment]
Actually, currently the juncture list should be ordered so that the most common kanjis are first. This nicely corresponds to the JLPT levels. The sorting is done by Lucene and is blazingly fast, so it's always done.
Of course, if this is not true, then there is a bug in Aedict. In that case just let me know the exact kanji. Thanks!

**Comment by Teomada** [comment]
Hi,
Yes I do acknowledge that some kind of logic is already applied to the sorting process. And in fact I might have been too anal on this. You find a JLPT4 or 5 kanji at the bottom of the list.
I raised it after noticing that for the following kanji the JLPT order is a it mixed, at least at the beginning

**Comment by Teomada** [comment]
Hi,
Yes I do acknowledge that some kind of logic is already applied to the sorting process. And in fact I might have been too anal on this. You won't find a JLPT4 or 5 kanji at the bottom of the list.
I raised it after noticing that for the following kanjis the JLPT order is a bit mixed, at least at the beginning:
雨 (ame): 2,1,1,2,3,1,
月 (tsuki): 5,4,3,3,4,3,4,
As said, it's not a big deal,more just an observation.
I'd still be interested to know what you mean by "most common kanji first". Is that based on a specific ranking?
As usual, thanx for your great support

**Comment by mvysny** [comment]
Yup, basically I found somewhere a list of 1000 most common kanjis, sorted from most common. The list is as follows:

日一国会人年大十二本中長出三同時政事自行社見月分議後前民生連五発間対上部東者党地合市業内相方四定今回新場金員九入選立開手米力学問高代明実円関決子動京全目表戦経通外最言氏現理調体化田当八六約主題下首意法不来作性的要用制治度務強気小七成期公持野協取都和統以機平総加山思家話世受区領多県続進正安設保改数記院女初北午指権心界支第産結百派点教報済書府活原先共得解名交資予川向際査勝面委告軍文反元重近千考判認画海参売利組知案道信策集在件団別物側任引使求所次水半品昨論計死官増係感特情投示変打男基私各始島直両朝革価式確村提運終挙果西勢減台広容必応演電歳住争談能無再位置企真流格有疑口過局少放税検藤町常校料沢裁状工建語球営空職証土与急止送援供可役構木割聞身費付施切由説転食比難防補車優夫研収断井何南石足違消境神番規術護展態導鮮備宅害配副算視条幹独警宮究育席輸訪楽起万着乗店述残想線率病農州武声質念待試族象銀域助労例衛然早張映限親額監環験追審商葉義伝働形景落欧担好退準賞訴辺造英被株頭技低毎医復仕去姿味負閣韓渡失移差衆個門写評課末守若脳極種美岡影命含福蔵量望松非撃佐核観察整段横融型白深字答夜製票況音申様財港識注呼渉達良響阪帰針専推谷古候史天階程満敗管値歌買突兵接請器士光討路悪科攻崎督授催細効図週積丸他及湾録処省旧室憲太橋歩離岸客風紙激否周師摘材登系批郎母易健黒火戸速存花春飛殺央券赤号単盟座青破編捜竹除完降超責並療従右修捕隊危採織森競拡故館振給屋介読弁根色友苦就迎走販園具左異歴辞将秋因献厳馬愛幅休維富浜父遺彼般未塁貿講邦舞林装諸夏素亡劇河遣航抗冷模雄適婦鉄寄益込顔緊類児余禁印逆王返標換久短油妻暴輪占宣背昭廃植熱宿薬伊江清習険頼僚覚吉盛船倍均億途圧芸許皇臨踏駅署抜壊債便伸留罪停興爆陸玉源儀波創障継筋狙帯延羽努固闘精則葬乱避普散司康測豊洋静善逮婚厚喜齢囲卒迫略承浮惑崩順紀聴脱旅絶級幸岩練押軽倒了庁博城患締等救執層版老令角絡損房募曲撤裏払削密庭徒措仏績築貨志混載昇池陣我勤為血遅抑幕居染温雑招奈季困星傷永択秀著徴誌庫弾償刊像功拠香欠更秘拒刑坂刻底賛塚致抱繰服犯尾描布恐寺鈴盤息宇項喪伴遠養懸戻街巨震願絵希越契掲躍棄欲痛触邸依籍汚縮還枚属笑互複慮郵束仲栄札枠似夕恵板列露沖探逃借緩節需骨射傾届曜遊迷夢巻購揮君燃充雨閉緒跡包駐貢鹿弱却端賃折紹獲郡併草徹飲貴埼衝焦奪雇災浦暮替析預焼簡譲称肉納樹挑章臓律誘紛貸至宗促慎控

Maybe the list needs to be reviewed whether it actually makes any sense and is not obsolete ;)
It is actually very easy to change the sort order, first by JLPT descending (so that JLPT5 kanjis are first), then by commonality. So, if you believe this sorting order makes more sense then I can change that. What do you think?

**Comment by Teomada** [comment]
Hi, yes if the effort is minimal I would appreciate if sorting is done by JLPT level as you indicated below. Thanks again!

**Comment by mvysny** [comment]
Sure, no problem ;)

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.29
