### ISSUE TITLE
Minor display issue in quick field list

### ISSUE THREAD

**Issue by mjaj** [mvysny/aedict#725]
On my tablet, when working in 3 column mode, the entries in the quick field list which do not fit into the line are not reasonably wrapped, resulting in some weird display, as shown here for the Halpern and the Kodansha entries. 
![screenshot_2017-01-31-22-39-51](https://cloud.githubusercontent.com/assets/15126895/22485829/701b32ec-e807-11e6-8c13-36e742c10a81.png)

The KanjiDictionary entry is completely unusable in this display mode.
Everything works well when columns are wide enough, i.e. in 2 column mode on my tablet.
This is a very low priority issue, so please consider this just as an information. Thanks for your great work on all the other more important features of Aedict.

**Comment by mvysny** [comment]
Oops :-D Sorry about that, and thanks for the screenshot. As a workaround you can force Aedict to show 2 columns - just press the upper-right "Overflow" button and there should be a configuration option for that.

Now, the straightforward fix would be simply to increase the minimum column width, thus having two columns in your tablet. However, it is very important for me to know your opinion on this: does it make sense to have these three columns in one page? If yes, then I'll rather fix the display of the Kanji column to not to waste so much space (well, that's needed anyway since that Kanji column code is really old ;). If no, I will also fix the logic which allots three columns on the first page and one column at the second page, making it balanced, to allot two columns per page.

Please let me know your opinion on this.

**Comment by mjaj** [comment]
Thanks for looking at this.
For me personally, the three column mode is very convenient, e.g. to see the buddies on the same screen. If I activate the option "Example sentences in the first tab", I can even get all information on one screen. However, this does not work anymore when looking at kanji details, with six blocks of information (kanji, radical, parts, junctures, words, examples). Also, on larger screens, I would consider a restriction to two columns a waste of space.  But, this is mainly a matter of my personal taste, and I could also get used to a different layout (as I have it on my smartphone anyway).
So, personally, I suggest not to remove the three column mode, but I can accept if you do so.
For the shown issue, the most obvious workaround is not to display these pieces of information permanently. I do sometimes want to know the number of the kanji in these dictionaries, but I can still easily access with information if it is not selected in the quick field list.

**Comment by mvysny** [comment]
Sure, I'll not remove the three column mode then. Instead, I'll fix the Kanji column to not go haywire when it's thin enough.

Just a hint: you can actually configure your Aedict to show only the information you are interested in. Just press the "(i)" icon below the kanji; in the list shown, just press the Pin/Unpin icon next to the piece of information. If the piece of information is unpinned, it will not appear in the quick field list.

**Comment by mvysny** [comment]
Fixed in 3.39.29:
![device-2017-02-05-024029](https://cloud.githubusercontent.com/assets/254091/22622756/97cc86ea-eb4c-11e6-970a-e7652ffd5567.png)

**Comment by mjaj** [comment]
Many thanks for fixing even this low priority issue. Great to see how dedicated you are to further improve this great app.

**Comment by mvysny** [comment]
@mjaj Thanks! Unfortunately since I'm with two kids, I no longer can develop as actively as I'd like to. There are lots of opened bugs laying around, and I only have time&energy to fix simple ones...
