### ISSUE TITLE
Example - wrong kana conversion in "I don't care for the way he talks"

### ISSUE THREAD

**Issue by Todew** [mvysny/aedict#753]
Negative is turned into affirmative.

**Comment by mvysny** [comment]
Do you mean this one? https://tatoeba.org/eng/sentences/show/287845 And do you mean the conversion of kiniiranai -> kiniiru?

**Comment by Todew** [comment]
Yes.
彼の話し方が気にいらないのです。
I'm every much a beginner but surely the conversion means the opposite?

Best wishes
Tony Woolf

**Comment by mvysny** [comment]
Sure, it does. The problem lies in the following. I'm using the data from the Tatoeba project: https://tatoeba.org/eng/downloads
I am extracting furigana from the `jpn_indices.tar.bz2` file, which a list of so-called B-lines (the B-line format is described here: http://www.edrdg.org/wiki/index.php/Sentence-Dictionary_Linking )

The B-line for this particular sentence is as follows:
`彼(かれ) の 話し方 が 気に入る{気にいらない} のだ{のです}`
That means that 気に入る is the dictionary form of 気にいらない. In order to get the reading from that I need to find 気に入る in JMDict and resolve the reading (which it does correctly, kiniiru) then grab the reading and match it somehow onto the "sentence form" of 気にいらない. In this particular case it is impossible since 入る is changed completely into いらない and my algorithm can't thus match that (it can match other cases and sometimes it does wonders, but in this case the stem is simply too different from the conjugated form and I try to avoid 'just guessing'). Thus, the *kiniiru* is kept as-is.

This issue has two possible solutions:
1. Do not provide any reading in this case. I think that possibly deconjugated reading is better than none - what do you think?
2. Contact guys from Tatoeba and let them include the conjugated reading of *kiniiranai* into the B-line somehow. This probably needs to be discussed with the Tatoeba guys since the B-Line has no support for including such information.

**Comment by mvysny** [comment]
Fixed! :-) Please wait until I will publish an updated Tatoeba dictionary files, then update the dictionaries in your phone's Aedict.
