### ISSUE TITLE
Example 彼は辞書を6冊以上持っている。translation

### ISSUE THREAD

**Issue by Todew** [mvysny/aedict#760]
６冊 Is translated as five (dictionaries).

**Comment by mvysny** [comment]
Thanks for letting me know. This seems to be the bug in the tatoeba data: if you open the example sentence in aedict and choose "show sentence on tatoeba web page" you'll see that the tatoeba page contains the issue as well.
Please can you contact tatoeba guys and let them know about the issue, so that everyone benefit from the fix? Thanks!

PS: the link to the sentence https://tatoeba.org/eng/sentences/show/104778
