### ISSUE TITLE
Aedict Reader Always Available setting not working

### ISSUE THREAD

**Issue by bgx90** [mvysny/aedict#766]
Android version: 6.0.1
Aedict version: 3.39.36
Aedict Reader version: 1.3.18

After updating Aedict Reader, the persistent notification for Reader does not appear when the Always Available and Watch Clipboard settings are enabled.

**Comment by mvysny** [comment]
Thank you, yes, that is kinda intentional, please see #765 for details. The icon in the taskbar is gone, but the persistent notification should be there. If it's not there, then it's a bug.

If you'd still like the icon to be present as well, just let me know and I'll add a configuration option for that.

**Comment by bgx90** [comment]
I see the notification now. It was not there before. I guess the previous lookup was cleared when the update installed and that the notification has reappeared now that I have looked something up with the reader. I am fine with the icon not showing in the taskbar. Thanks.

**Comment by mvysny** [comment]
Thanks for letting me know! Upon update, Android kills the app itself, which then probably clears the notification as well. After update the app is probably not automatically started and thus the notification won't appear until later on when you start it manually. I don't think there is much I can do about this.
