### ISSUE TITLE
Random word notification from notepads

### ISSUE THREAD

**Issue by eji30** [mvysny/aedict#768]
Suggestion: can you add a notification that shows a random word from your notepads? I think that would be a nice addition in learning Japanese.

I'm thinking maybe have an option to check which notepads to include on getting a random word from, then an option to show it in notification (and of course an option to not show it in statusbar like my request in Aedict reader). Then on the notification you can see the kanji, kana, and the definition of that random word (or maybe it can be customized as to which to show?). For the interval on when to show it, I think the basic one that comes to mind is per 1 day (or again customizable).

I hope if not all, at least a part of this suggestion will be considered. Thank you very much!

Aedict version: 3.39.38

**Comment by mvysny** [comment]
Hey, that's a really nice feature! There is Settings / GUI Tuning / Always Available which shows the notification; however currently the notification only shows a dull "Aedict" text, without any further information. The notification itself could be made to show the random entry from your Notepad instead.

Let's keep the prototype simple: the text will change once per day, and it will show a random entry from the whole notepad. I'll also hide the notification icon by default, we'll see what kind of shitstorm this will generate :-D (similar request to Aedict Reader actually only generated one bug report #766 that's managable).

**Comment by mvysny** [comment]
I just wasted two hours trying to figure out how to create an Alarm which:

a) triggers once per day,
b) is not canceled and recreated when Android kills Aedict and launches it back
c) Survives Aedict killing

Fuck Android. AlarmManager has the worst API I've seen. PendingIntent, Intent, action, IntentFilter, total insanity. And I'm pretty sure that on some fucking phone this won't work. I have zero further interest in developing on that piece of shit Android.

Fixed in Aedict 3.39.39
