### ISSUE TITLE
Maybe Aedict Reader Popup shouldn't appear when Korean text is copied to clipboard

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#774]
When the "Watch Clipboard" feature is enabled, the Aedict Reader Popup appears when Japanese text is copied to the clipboard, and not when a string containing only English text is copied. This is very helpful.

But I notice that it also pops up when a string containing only Korean Hangul characters is copied (for example: 안녕 ). I wonder if the pop-up could be disabled in such cases?

**Comment by mvysny** [comment]
Sure, thanks! Actually the detection should be there, but it probably mistakenly takes Hangul for kanji. I need to fix the kanji detection algorithm; perhaps to this: https://stackoverflow.com/questions/19899554/unicode-range-for-japanese

I wonder if the range 4e00-9faf really covers all kanji - I'm a bit sceptical since I saw some kanjis in jmdict and kanjidic spanning over 10000...

**Comment by mvysny** [comment]
Apparently Kanjidic lists kanjis outside of that range, say 𪚲. So I need to manually exclude the hangul range. Thanks, fixed.

**Comment by mikemorr** [comment]
I notice the reader pops up when I copy Regional Indicator Symbols (used to display national flags), such as 🇺 or 🇺🇸

**Comment by mvysny** [comment]
Should be fixed in Reader 1.3.21
