### ISSUE TITLE
Aedict Reader Problem on Huawei Medaipad M3

### ISSUE THREAD

**Issue by rojaKaj** [mvysny/aedict#780]
Device: Huawei Mediapad M3 (enabled Dropzone management, permitted Draw over app)
Aedict Reader properly works after starting, but in a couple minutes app itself stops poping up.
Best Regards,
KJR.

[log.txt](https://github.com/mvysny/aedict/files/1161200/log.txt)

### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play, Blackberry store or Amazon App store.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Income from Google Play and other stores is rather small, and is made even smaller by the 30% fee charged by Google and 20% VAT charged in most countries. Please consider supporting the project on Patreon: 

https://www.patreon.com/bePatron?u=2914375

**Comment by rojaKaj** [comment]
[log.txt](https://github.com/mvysny/aedict/files/1161194/log.txt)

**Comment by mvysny** [comment]
Thanks! Hmm, I have checked the logs and there are no exceptions. It looks as if Aedict Reader has been killed by your phone every couple of minutes. Do you have some sort of task manager? Or perhaps your phone is really low on memory? Do you have the Reader's Setting "Watch Clipboard" and "Always available" checked? If yes, then the Reader will start Android Service - can you please check that the Reader Service is running? If not, perhaps your phone is low on memory and is just killing all apps in order to free the memory?
Hmm, not really - the tablet looks pretty nifty at 4GB of memory. The video buffers are probably using 1,1GB with that nifty resolution, but that would still leave us with 2,9GB of memory free for apps. So it should be fine unless you use some kind of "Task Killer" app?

**Comment by rojaKaj** [comment]
Thank for your response.
1. No Task Manager App installed.2. Free RAM = 2.2 GB3. "Watch Clipboard" and "Always available" was checked. App Notification Icon showed, but it stopped popping and loss notification icon in a couple seconds.4. Aedict Reader Service (Floating Window Service) still running, but not popping.5. I never used "Task Killer" app.
KJR

**Comment by rojaKaj** [comment]
For your information.
After a few minutes, Aedict Reader Service stopped running.
KJR
⁣Sent from BlueMail ​

**Comment by mvysny** [comment]
Something is killing the service then. Or perhaps it stops on its own? I need to investigate.

**Comment by rojaKaj** [comment]
It stopped poping up, even though "Floating window service", "sk.baka.aedictreader" and "sk.baka.aedict3" running.

⁣Sent from BlueMail ​

**Comment by mvysny** [comment]
The floating window service is important to be running - if it's running then the reader should work. I wonder what can cause the reader to stop receiving clipboard changes notifications...

**Comment by rojaKaj** [comment]
Google Translate (Tap to Translate feature) had this problem too.Regret that cannot use app on this new device.

**Comment by mvysny** [comment]
I am very sorry to hear that. However if the Google translate app does not work on your phone as well, then that indicates an Android problem in your device. Please try to open a bug report both on Android bug tracker, and in your phone's vendor bug tracker. Also please let me know if you'd like a refund, and send me the transaction number.

**Comment by Enyby** [comment]
View removed by something tagged as "ash":
```
07-20 11:24:15.112  1765  1997 I ash     : view remove pid:22071 uid:10099
```
Pid 22071 is Aedict:
```
07-20 11:24:12.876 22071 22071 I AedictRea:FloaterServi*: Launching floater with 不適切
```
This "ash" even can close another apps. From other log: 
https://gist.github.com/TestologyQA/ab98ceb43996432c472cc41eae69d5bc
```
12-04 11:33:46.438  1900  2151 I ash     : com.android.gallery3d { running duration=4231 } transition to: end, reason:stop_ash
12-04 11:33:46.438  1900  2151 I ash     : com.seatgeek.android.beta { running duration=4229 } transition to: end, reason:stop_ash
12-04 11:33:46.438 1900 2151 I ash : com.stupeflix.replay { running duration=4225 } transition to: end, reason:stop_ash
```
Judging by pid this is part of the system, and not a third-party application, since there are entries from this pid for AppManager.

ash is not part of the android. This is something from the vendor.

**Comment by mvysny** [comment]
Please try reading FAQ: http://aedict.eu/reader/faq.html . There is something called Dropzone Management which may help.
