### ISSUE TITLE
Word of the Day

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#781]
Very nice feature.
But would it be possible to open Aedict on this word when clicking on it?

**Comment by mvysny** [comment]
Ah true, that makes sense. Currently the original functionality is probably there, which simply launches the Aedict search screen.

**Comment by andrejrenard** [comment]
Can you change the font size for the title and the word. I would rather prefer greater kanjis.
Or perhaps: 
Word of the Day: <<word>>
<<translation>> <<_(grammar)_>>

**Comment by mvysny** [comment]
Changing the font size requires custom layouts (as per https://stackoverflow.com/questions/24320601/how-to-style-notification-message-for-pushnotification ), however custom layouts are only supported from Android 7 (sdk 24) which is a no-no for Aedict (because of #741 ). So I can only change the notification title and text as you suggest.

Regarding the navigation: historically, Aedict opened the search screen when clicking the notification. I'd like to preserve that for backwards compatibility. I'll thus add a setting for this - checking this option will cause Aedict to open the word of the day instead of the search screen.

**Comment by mvysny** [comment]
Added a setting which, when checked, will make Aedict open the Word Of The Day details. You can find the setting in Settings / GUI Tuning / Notification opens Word Of The Day.

Implemented in Aedict 3.42
