### ISSUE TITLE
"Read from Preferences.xml value" issue

### ISSUE THREAD

**Issue by dorearendil** [mvysny/aedict#789]
Hi Martin and others,

After having been using Aedict 2 for some months, I finally decided to take the leap and buy Aedict 3.
The main reason that prompted me to do this is the long, long list of words I have accumulated in my Aedict 2 notepad. I want to export these words into Anki cards.
So I followed the relevant instructions on the Aedict FAQ.

However, when I try importing the backup version of my Aedict 2 notepad into Aedict 3, there is no "Import Notepad" option among the action bar menu items. I found a notepad.backup file at the root of my /sdcard/aedict folder, tried opening it, and it does seem to be empty.

So I tried to find the "/data/data/sk.baka.aedict/shared_prefs/sk.baka.aedict_preferences.xml" file mentioned in the FAQ, but this /sk.baka.aedict/ directory is nowhere in sight... (I do see the following one though: /sdcard/Android/data/sk.bakaedict3/)

Am I looking in the wrong place?
Cheers,
D

**Comment by mvysny** [comment]
Oh goodies, I'm very sorry but I have removed that functionality at some point this year; I haven't anticipated that somebody would still use Aedict 2 in 2017, even less to migrate to Aedict 3 :-( So, I guess the support for "Import Notepad" has been removed; let me check and let me update the documentation accordingly.

The `preferences.xml` is actually something quite different - it is just a list of settings for the Aedict 3 app. Let me revisit the FAQ.

**Comment by dorearendil** [comment]
So do you mean that there is another way to import my Aedict 2 notepad
into Aedict 3? I must confess I sincerely hope there is, as the
import/export info in the Aedict FAQ was basically what made me buy
Aedict 3 :D
Please let me know if there's a workaround!

**Comment by mvysny** [comment]
Sorry, there is no workaround as far as I know. If Aedict 2 backup file is empty, then you have been bitten by a bug in Aedict 2 which creates empty backups instead of a proper notepad backup; Aedict 3 can't currently import stuff from Aedict 2. I don't remember but if Aedict 2 can export notepad as CSV then I can create some kind of CSV import, but that would require time which I do not have. I can't even provide an estimate on this since I only have a very little free time which is only spent on Aedict bug fixing.

I'm very sorry, if you want refund on Aedict 3, just let me know.

**Comment by dorearendil** [comment]
Hi Martin,
Thank you for your reply.
It's disappointing that I can't do anything to deal with this bug, but
I understand that you have already been investing much of your time
and efforts in developing Aedict. I'm happy to view my purchase of
Aedict 3 as a small gesture of encouragement and reward for your great
work.

Best,
Dorian

**Comment by mvysny** [comment]
Thank you for being so understanding, and thank you for your support. I am very sorry and very sad that I couldn't be able to help you; unfortunately such migration is very hard due to differences between those data files.

Yet, you may find it easier to add the missing entries into Aedict Online, then sync them with your phone. Hopefully this actually still works... You can read more here: https://www.patreon.com/aedict/posts

**Comment by dorearendil** [comment]
Sorry, I'm not sure I understand your last advice well...
Do you mean there is a way to automatically upload the Aedict 2
notepad entries to Aedict Online? As far as I can see, the only option
in the Aedict 2 "Expert Settings" is "Sort results" -- no "User Data"
item... Am I missing something?

**Comment by mvysny** [comment]
Nope, unfortunately there is no automatic way. Yet, if you plan to manually add those entries, adding those entries to Aedict Online via desktop keyboard may be less painful.

**Comment by dorearendil** [comment]
Understood.

Alas, I'm afraid to report Aedict Online doesn't work so well on my
laptop (Ubuntu) -- the dictionary generally starts searching
immediately as soon as I input a single character/kana into the search
field (in other words, it doesn't wait until the entire word has been
entered before performing the search). For instance, if I try entering
医者, the dictionary will return entries for the kana い...
Most of the time, the search ends up with the Internal Error message:
"NullPointerException - Cannot provide an ID for a null item"

I know Aedict Online is only in Beta as of yet. I'm sure it will
greatly improve in the future :)
For now, I'll just create my Anki cards the old way: from scratch!
Maybe I learn better this way, anyhow.

Cheers,
D

**Comment by mvysny** [comment]
Ah, I'm sorry for that. I heard that Aedict Online does not work that great with japanese keyboard, but I was not aware that it outright crashes. Can you please open a new bug for that Aedict Online issue? I'm also on Ubuntu, so just let me know which jp keyboard are you using so that I can reproduce the crash. Thanks!
