### ISSUE TITLE
Quiz 

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#798]
Hi Martin,

I am more and more using the English first quiz on my tablet, but...

The keyboard has to be closed (hidden)  to access the bottom buttons. Pretty annoying. Perhaps moving the button bar at screen top or even better, keyboard enter = enter button?

It would be nice to have an audio button. Even better to have an option for automatically spelling the first most frequent pronunciation when answer is shown.

Answer is green when only part of a correct answer is entered (for example: onion -> tama for tamanegi). Would be better to consider such an answer as false (red).

It would be nice to have an option to replace the drawing pad by more infos on the answer (examples panel would be super)

Best regards
Andre

**Comment by mvysny** [comment]
> The keyboard has to be closed (hidden) to access the bottom buttons. Pretty annoying. Perhaps moving the button bar at screen top or even better, keyboard enter = enter button?

I can't move those buttons to the top since that would make them hardly accessible with your thumb. However, I have changed the screen behavior for quiz to `adjustResize`, so that the view is shrink in order to avoid being covered by the virtual keyboard. This effectively hides the kanjipad but in general it works pretty well. Let's test this mode a bit.

> It would be nice to have an option to replace the drawing pad by more infos on the answer (examples panel would be super)

Well, other users would like some other content perhaps and creating a configuration option for this would make Aedict even more hard to use; I believe the info button showing a full information about the entry should be enough - it is only one tap away after all.

> It would be nice to have an audio button. Even better to have an option for automatically spelling the first most frequent pronunciation when answer is shown.

Yeah, that's a nice idea, I can add the audio button.

> Answer is green when only part of a correct answer is entered (for example: onion -> tama for tamanegi). Would be better to consider such an answer as false (red).

Interesting, let me fix that.

**Comment by mvysny** [comment]
Implemented in Aedict 3.44. Just head to Settings / Quiz Settings and make sure that "Speak Answer" is checked.
