### ISSUE TITLE
Blackberry 10 version kanjipad issue and feature suggestion

### ISSUE THREAD

**Issue by neku14** [mvysny/aedict#807]
Hi, i want to report an issue and suggest feature.

I'm using aedict3 on blackberry 10 and the kanjipad seems to doesn't recognize some kanji, for example 場and　喧. When I try to search those kanji in aedict online, they come up within the first to five kanji result, while in blackberry I can not find them. Here's the screenshot:
![bb10 aedict 1](https://user-images.githubusercontent.com/33146144/32092031-62c221dc-bb29-11e7-9ba7-1e6e2a6e7b33.png)

![bb10 aedict 2](https://user-images.githubusercontent.com/33146144/32092096-9371f8b6-bb29-11e7-85da-d5f2a8baebb4.png)

![aedict online 1](https://user-images.githubusercontent.com/33146144/32092123-b52f13da-bb29-11e7-9b1b-bae2ae59eb97.png)

![aedict online 2](https://user-images.githubusercontent.com/33146144/32092125-b96ea8f2-bb29-11e7-86ce-a107bfb901a6.png)

Did you update the handwriting recognition algorythm? Could you update the blackberry version? And I read that aedict online is the online version of android's aedict, so that means in android aedict those kanji will show up in search using handwriting?

I want to suggest a feature regarding japanese name dictionary. The problem is that in aedict when we want to search japanese names, we have to enable the name dictionary, and that means getting much more search result, making the screen so cluttered. I know we can disable the other dictionary, but it's cumbersome to go back and forth enabling the dictionary. If you look at jisho online dictionary they have categories in search box, so that when we want to search name only, all we have to do is use the category and we get clearer result. In midori and shirabe jisho ios app, they have a toggle to turn the search from normal search to name only search. If you can add that feature, it will make searching for names easier. I think this feature is important, since as far as I know, only aedict3 has dictionary for japanese names.

Thank you for the app and your time.

**Comment by mvysny** [comment]
Hi, thanks for letting me know. Regarding the first question about the kanjipad. Yes, Aedict Online uses the more accurate http://aedict.eu/kanjipadextension ; however since that app has no UI I can't sell it on Blackberry market. Also, the Blackberry market sales are so low it is not feasible to maintain the port unfortunately.

Regarding the name search: you can do that easily; just hit the "filter" or "Advanced Search Settings" upper-right menu item (looks like a wifi signal icon); then when you select "Search In" "Dict", then there would be the "Dictionary" Check box which will allow you to quickly pick dictionaries where to search in. Please see the attached screenshot.
![screenshot_20171027-163604](https://user-images.githubusercontent.com/254091/32106716-1ce5edea-bb35-11e7-97c1-62d339fd5acb.png)

**Comment by neku14** [comment]
I see, too bad about blackberry :-D

But I assume the internal kanjipad between android version and blackberry version is using the same algorithm for  recognition? I believe I was using the correct stroke order and count for those kanji and yet the it doesn't return the kanji I was looking for. Does the algorithm check for size of the handwriting or the direction of the stroke? I mean maybe my handwriting was bad, but I've tried a couple of times and still it doesn't give me the result I was looking for. Could you test them on your device using the internal kanjipad? And if you can get the kanji, please attach a screenshot so I can try it too. I know you can use the extension, but I prefer using the strict algorithm, which kinda enforce you to write kanji the correct way. Thank you.

**Comment by mvysny** [comment]
> I see, too bad about blackberry :-D

Yeah, unfortunately the earnings for three years so far has been maybe $50 :-D Quite infeasible.

> But I assume the internal kanjipad between android version and blackberry version is using the same algorithm for recognition?

Yes, exactly the same.

> I believe I was using the correct stroke order and count for those kanji and yet the it doesn't return the kanji I was looking for.

That is quite possible. I've tried on both of my phones with the internal kanjipad, and I was unable to find the kanji 場 (see the screenshot). I will try with the Kanjipad Extension and I'll post more. The reason for that is that those two algorithms are completely different in nature and thus the input kanji set is different (the Kanjipad Extension uses the KanjiVG SVG drawings which is more complete; the internal kanjipad is "dumber" and uses different input which is far less complete). Therefore, it is entirely possible that the 場 kanji is only present in KanjiVG, and not in the input kanjiset of the internal kanjipad algorithm.

![device-2017-10-28-122348](https://user-images.githubusercontent.com/254091/32133152-e4a51e3c-bbda-11e7-98bc-9b47bec79ca8.png)

> Does the algorithm check for size of the handwriting or the direction of the stroke? I mean maybe my handwriting was bad, but I've tried a couple of times and still it doesn't give me the result I was looking for.

There is a very important difference, hinted in bug #139 . When an algorithm matches the kanji, there are two modes of operation:

* The search mode, which tries to find a kanji vaguely resembling the drawing. Here the user wishes to find a kanji he sees; the kanji may not be necessarily drawn properly.
* The verification mode, where the algorithm checks the drawing against a known kanjis, to verify drawing accuracy, stroke direction and everything. Here, the user wishes to learn how to draw a pre-known kanji properly.

The primary function of the kanjipad is to search for kanjis, hence mode 1. Both http://aedict.eu/kanjidrawpractice/index.html and Aedict in Quiz mode (I guess the "Draw Kanji Practice" mode, but you must enable Settings / Quiz / Proper Draw Check.

>  I know you can use the extension, but I prefer using the strict algorithm, which kinda enforce you to write kanji the correct way. 

That is unfortunately untrue. The internal algorithm is not actually stricter - it still operates in the "search" mode and thus will try to match as many kanjis as possible. It is merely dumber, older and operates on a smaller set of kanjis.

**Comment by mvysny** [comment]
The "Kanjipad Extension" algorithm operates on a bigger kanji set and is thus able to find the required kanji.
![device-2017-10-28-122817](https://user-images.githubusercontent.com/254091/32133184-8ca06948-bbdb-11e7-9532-41cae4b024be.png)

**Comment by mvysny** [comment]
What version of Aedict is there on Blackberry? I think it's quite an old one; maybe I can at least upgrade it to the newest one.

**Comment by neku14** [comment]
Blackberry version is 1.3.3926.0 updated September 23 2016. I appreciate it if you could update the blackberry version, though I'm thinking of buying aedict on play store too :-D

Doesn't that mean the internal kanjipad is flawed? Uhh no offense here, but from a buyer's perspective isn't it looks like you're forcing people to buy the kanjipad extension? The internal kanjipad is flawed in that it cannot find some kanji while the kanjipad extension is useful when we don't know how a kanji is written (stroke order and count) and has more kanji, but it's another paid app not included within aedict itself. Maybe you could change the internal algorithm to a better one, but still requires precise stroke order and count and keep the extension as a separate apps that has more tolerance on stroke order and count, or replace the internal kanjipad with the extension and raise the price of aedict, so there's no need for another kanjipad extension.

Don't take my suggestion as offense, I will also buy the kanjipad extension for searching kanjis I don't know how to write when I buy aedict on play store. It's just that in the state aedict is right now, it feels like we are forced to buy the kanjipad extension too.  I just want aedict to be better since this app is going to be my app of choice for japanese dictionary. Aedict is really good in comparison than most japanese dictionary on play store. Most of them doesn't have an internal handwriting recognition. Although there's google handwriting app, I prefer your take that the app itself has handwriting recognition. Before google released it's handwriting app, most dictionaries were unusable for searching kanjis that we don't know how to read. Hopefully you will keep develop aedict and make it better. :-D Best regards.

**Comment by mvysny** [comment]
> Blackberry version is 1.3.3926.0 updated September 23 2016. I appreciate it if you could update the blackberry version, though I'm thinking of buying aedict on play store too :-D

Let me try whether the Blackberry build still works - if yes, I can update ;)

> Doesn't that mean the internal kanjipad is flawed?

Not really. It is merely an older algorithm which I downloaded off the internet somewhere, along with the data files. So actually I have no idea what kanji set it detects, and how precise it is. The new algorithm lists all kanjis from KanjiVG so it's easy to check the kanji set, but it's hard to actually verify the accuracy. You see, such algorithms are typically fuzzy and only assign some matching score 0..100; then I'll show the kanjis based on highest score. But that makes those algorithms extremely hard to compare since I would need to have a large set of drawings. And thus, I am unable to say which algorithm is better: the internal one may match some kanjis better than the paid extension.

Now since I don't know which algorithm is better, how can I market the extension as an improvement? You're right, I can't, and it is completely unfair to you as the user. Please believe there was no evil intent; I do believe the extension to do better job finding kanjis, and I merely wanted to give the users the opportunity to choose for themselves, while raising some money for further development. But now I understand the situation is not optimal and I'm open to suggestions on how to improve it.

Anyways, thank you so much for your praise and understanding, I'm happy that Aedict works for you and I'm flattered that you believe it does the job best.

**Comment by neku14** [comment]
> Please believe there was no evil intent

Of course I believe you, it's just the situation is kinda giving the vibe (though I believe it's not on purpose)

Here's my opionion on the algorithm:

> Now since I don't know which algorithm is better, how can I market the extension as an improvement? 

True, to do a comparison we're gonna have to do drawing test on both of them, which is kinda hard to do given how many kanjis are there. But let's just see by the algorithm itself. The internal kanjipad uses old algorithm and how old is that? I mean when was it last updated? If it's been updated since you downloaded it, did you ever update the algorithm? And the extension uses kanjivg by ulrich apel, which is more recent? I tried to do a little searching and it seems it was last updated on 2016/04/26 (link : https://github.com/KanjiVG/kanjivg/releases).

> the internal one may match some kanjis better than the paid extension

Yes, maybe. And to prove which is better, again, we have to do tests. But the fact that the extension uses the newer and recently updated kanjivg is a sign that the extension is better (not yet proven though). And right now we only have two information to decide which is better:

1. The kanji 場 and　喧 cannot be found using the internal kanjipad, no matter how many times I've tried, while the extension, though may be not perfect (by your screenshot it's not even in the top row result), get the jobs done.

2. The internal kanjipad uses older algorithm, while the extension uses newer algorithm.

Thus I think it's kinda pointless to have the internal kanjipad at all. I don't know technical stuff like, maybe it's easier to update the kanjipad as an extension than if the kanjipad is also part of the main app. Maybe you have another reason to use extension rather than integrating it into the main app. The ocr is definitely better as an extension, since we don't know for sure if everybody is going to use it. But I think the kanjipad is an integral part of a japanese dictionary. Yes we can use skip and radicals to search for kanji, but I think handwriting is faster.

You can update the internal kanjipad algorithm if it got updated since you download it and keep the extension as a separate. If the older algorithm was never updated anymore, I recommend using the extension as the primary and sole kanjipad by integrating it to aedict. By doing so, we can remove some confusion and the situation which kinda seems like forcing users to get the extension. You can raise the price of aedict to compensate for it. Or you can keep the price, but you will lose some money. So I will leave the decision to you, I'm just giving my thought. :-D

**Comment by mvysny** [comment]
Hm, seems reasonable. I need to iron out the financial aspect but this generally can be done. Just a thought: what about users who would like to keep the old algorithm, for whatever reason?

The old algorithm haven't been updated since it's inclusion (nor algorithm neither the data files) so I guess it's pretty old. Yet I don't think we should compare the age of algorithm - it's the matching performance that counts. Hmm let me try to extract the kanji set used by the old algorithm and compare it to the most current kanjivg.

**Comment by neku14** [comment]
> Just a thought: what about users who would like to keep the old algorithm, for whatever reason?

I can't find any reason to keep the old algorithm, but I can only speak for myself, not others. But I have an idea if you want to accommodate those who want to keep it for whatever reason.

> The old algorithm haven't been updated since it's inclusion (nor algorithm neither the data files) so I guess it's pretty old. Yet I don't think we should compare the age of algorithm - it's the matching performance that counts. Hmm let me try to extract the kanji set used by the old algorithm and compare it to the most current kanjivg.

Ahh sorry, I guess my choice of word is wrong. You're right that the age of algorithm isn't what we should compare. If we go by human standards, the older one should win, as in life older people has more experience than younger people :-D So let me change it. What we should compare is the last updated date I think. The older algorithm hasn't been updated for a long time, so it could mean that it isn't actively developed anymore. That means, this bug or incomplete database (I don't know what we should call this) won't be fixed. While the algorithm based on kanjivg has been updated more recently. I found another kanji that cannot be found in the older algorithm. It's a 29 stroke kanji, 鬱. Heres the screenshot using internal kanjipad:

![screenshot_20171030-103856](https://user-images.githubusercontent.com/33146144/32152918-fa9a1ab6-bd61-11e7-8bd2-7a6ade8bbffd.png)

Here's using the extension:

![screenshot_20171030-103927](https://user-images.githubusercontent.com/33146144/32152923-04e5fd0a-bd62-11e7-8b3a-bd5d1110bdd0.png)

Now how to accommodate those who prefer the old algorithm. What if the internal algorithm and the extension is reversed? The newer algorithm is used as the internal kanjipad and the older algortihm is used as an extension. You can raise the price of aedict or keep it, I'll leave the financial aspect decision to you. But the extension becomes free, since it's an older algorithm. You can add in the description saying it's the old algorithm for whoever wants to use it for whatever reason and that it is incomplete that it cannot find some kanji. That way you can accommodate those who want to use the older algorithm and not having this not optimal situation. When someone tries using the free older algorithm extension, they won't have anything to complain, since it's free and uses older algorithm. The situation we have now is someone buys aedict and cannot find some kanji, and they think they are forced to buy the extension to find some kanji using handwriting since the internal kanjipad is incomplete.

**Comment by mvysny** [comment]
Since BlackBerry OS is dead and Aedict 3 has sold 33 copies for BlackBerry OS, I am discontinuing any form of support on BlackBerry OS effectively now. An update to the newest 3.45 has been pushed but that's it - no more updates will come. Since I do not own BlackBerry myself nor I have any kind of knowledge about the platform and its replacement/future course, I can not suggest any hints.

**Comment by mvysny** [comment]
The way of paying for Aedict has been changed. Now all advanced features are being unified under the "Aedict Ultimate" banner. When you purchase Aedict Ultimate, the more advanced algorithm kicks in automatically. There is no Aedict KanjiPad Extension anymore - it's discontinued and no longer used. I think this solution also solves this issue. Closing as fixed in Aedict 3.50, please let me know if there is anything more.
