### ISSUE TITLE
は as ha instead of wa

### ISSUE THREAD

**Issue by PuduC** [mvysny/aedict#810]
The example sentences seem to always translate は as ha instead of wa. Is there any easy fix for this?

cheers

**Comment by mvysny** [comment]
Hi, Let me look at that. Can you please provide an example for that behavior please?

**Comment by PuduC** [comment]
Thanks for quick response!

<img width="384" alt="screenshot_20171110-114453" src="https://user-images.githubusercontent.com/33548417/32669493-bee7a14a-c60e-11e7-9bcd-e15cff950bbc.png">

<img width="384" alt="screenshot_20171110-114549" src="https://user-images.githubusercontent.com/33548417/32669506-c6f7d9c2-c60e-11e7-8c15-6db48e1ef231.png">

**Comment by mvysny** [comment]
Ah, yeah... The romanization engine is very simple and blindly translates は as ha. Unfortunately, to properly romanize は to wa it would have to know that a particular は acts as a particle in a sentence; that's impossible without actual knowledge of the sentence structure.

Maybe I could reconstruct this information from the sentence analysis, but that's quite a lot of effort. The romaji is actually intended only for beginners who struggle with hiragana; I expect learners to actually turn off this feature as they learn hiragana. So it seems to me like a lot of effort for something that's only used briefly at the beginning of the learning process... But let me take a look - maybe this might be actually quite easy to fix.

**Comment by PuduC** [comment]
Yes, I guessed that it was going to be difficult to do - having to know the meaning of each sentence, not just the individual word meanings. 

It's not a big deal - you're correct in that it's far better to keep romanization turned off. I actually only noticed it this week becauseI started exporting vocabulary to Anki and the romaji stood out at me on the Anki cards.

Thanks for addressing my question though, much appreciated.  Have a great weekend.

**Comment by mvysny** [comment]
No worries, have a nice weekend, too ;)

**Comment by mvysny** [comment]
The case of "konnichiwa" is unfortunately not possible to fix since that information is missing from the JMDict file. I could add a manual workarounds into the Aedict code-base for that, but that's tedious and error-prone. It would be better for Jim Breen to add this kind of information to the JMDict file.
Relevant entry quote:
```xml
<entry>
<ent_seq>1289400</ent_seq>
<k_ele>
<keb>今日は</keb>
<ke_pri>ichi1</ke_pri>
</k_ele>
<r_ele>
<reb>こんにちは</reb>
<re_pri>ichi1</re_pri>
</r_ele>
<r_ele>
<reb>こんちは</reb>
</r_ele>
<sense>
<pos>&int;</pos>
<misc>&uk;</misc>
<s_inf>こんちは is col.</s_inf>
<gloss>hello</gloss>
<gloss>good day (daytime greeting)</gloss>
</sense>
</entry>
```

**Comment by mvysny** [comment]
In case of example sentences, for quite a lot of those actually there is a proper analysis present, which clearly indicates the standalone "は" particle. When romanizing, I could make use of that information. Let me check.

**Comment by mvysny** [comment]
I need to keep the romanization function as simple as possible, in order to be fast. The only solution would thus be to attach custom romanization for every example sentence, both in Hepburn, Kunrei-shiki and Nihon-shiki, which would further enlarge the already big dictionary file. I believe that this cost outweights the minor benefit of having a proper romanization of wa.

With your approval I'm thus marking this as won't fix - please feel free to reopen.
