### ISSUE TITLE
Can't choose the note card type for Anki Export

### ISSUE THREAD

**Issue by Vaanen** [mvysny/aedict#813]
Hey, so i love the app, however since a few updates, it seems it's not possible to choose the note type anymore. It's an issue because someimtes, i don't want recall on some words and it forces you to use one and only same card type for every export.

i love the apl by the way don't worry haha, just it would be awesome to be able to choose the card type

**Comment by mvysny** [comment]
Hi there! Thanks, I'm very happy you like this little app :)

This export-related change has been a change introduced by Tim of AnkiDroid quite some time ago. The gist is that you no longer export cards as their front+back, since that type of export fixes the card contents. After the export, you can't choose the contents of the front+back anymore in AnkiDroid.

What Aedict+AnkiDroid does today is that it exports all the raw values instead - the kanji, readings, SKIP codes (for kanjis) etc etc. It also creates three predefined card types in AnkiDroid (kanji/en+reading, kanji+reading/en, en/kanji+reading). That allows you to switch the quiz type straight from AnkiDroid: you select the card type and AnkiDroid renders it and populates it with the raw data it obtained from Aedict. This also allows you to create additional card types right in AnkiDroid, to suit your learning needs.
