### ISSUE TITLE
"Export to AnkiDroid" exports multiple cards

### ISSUE THREAD

**Issue by kymatx** [mvysny/aedict#833]
Since the latest update Aedict exports 3 cards instead of just one card as you can see in the attached screenshot. One card without furigana, one card with furigana and one card with the translation on the front. Would be nice if you could fix that.
Thanks for working on this great app, it makes studying a lot easier for me.

![anki](https://user-images.githubusercontent.com/17027528/39647443-4b2547ac-4fdf-11e8-988f-edb84d3712f9.png)

**Comment by kymatx** [comment]
I already found a solution for this. I just had to delete 2 of the 3 card templates in anki for sk.baka.aedict3v8

**Comment by mvysny** [comment]
Hi, yes, that is correct. Aedict creates a card model with three card templates, so that you can choose how you would like to be tested. However, Aedict then exports every entry only once; you can then choose any of the three card templates to render the entry. So, the data is exported only once, but there are three ways of visualize of the data.

Anki gives you the freedom to remove card templates you don't use, or create new ones you miss. Aedict won't re-create card templates once they are created.

Since you've found a solution to your issue, I'll close this.
