### ISSUE TITLE
When I backup my notepad to dropbox, it goes to a wierd subfolder in dropbox.  I can't figure out how to change the target folder in dropbox.  Do you have any guidance on this?

### ISSUE THREAD

**Issue by astrometab** [mvysny/aedict#846]
### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Please provide:
1. Your phone brand and maker
2. The exact Android version.
3. A screenshot if possible; even better, a youtube video demonstrating the issue.
4. A full description of the issue you're experiencing. For example: I used to read manga with the MangaReader Android app, while having the Aedict Reader popup floating. I could click the Reader window, select word search and type in the word to look up. Now the virtual keyboard doesn't pop up. You suck :-D

**Comment by mvysny** [comment]
I think you mean the `Apps/Aedict` folder. There is no setting to change that setting unfortunately. Recent Aedict even doesn't have any support for Dropbox since the new way of storing data into the UMN database is incompatible with any kind of backup. There will however be a possibility to sync your data with a server, either Aedict Online-hosted or you will be able to run your own sync server. More details coming up.
Unfortunately I will not be adding Dropbox integration since storing notepad into a file leads to OutOfMemory errors, file-grained sync works horribly wrong and UMN doesn't support backups. Closing.
