### ISSUE TITLE
Reader: fails to deinflect 超え

### ISSUE THREAD

**Issue by jimoow** [mvysny/aedict#860]
Phone: Freetel RAIJIN FTJ162E

The exact Android version: 7.0 Security patch level 5 Aug 2017

Bug requested by Martin from #859

Using Reader Aedict will try to search for 超え and it fails to deinflect it to 超える (please file a separate bug for this); thus it breaks it up into two "words" 超 and え and looks them up in the JMDict dictionary

**Comment by mvysny** [comment]
Hmm, according to my sources the Base4 form only applies to godan verbs: http://www.baka.sk/~tmath/language/jpverbs/lesson50.htm . Since 超える is ichidan it cannot use the Base4 form. Or can it? We should verify this with a Japanese authority. If you are attending japanese class courses, could you verify this with your teacher please?

**Comment by jimoow** [comment]
Hmmm, I just asked a native speaker they told me 超え in this case is used as
a noun. This can be done for ichidan verbs (but not for all of them).
More research required...

**Comment by mvysny** [comment]
Currently 越える is only marked as `v1 vt` which doesn't specify that the verb can be used as a noun 越え. Since JMDict is missing the 越え noun entry, the analyzer has no way of knowing that a deinflection such as 越え -> 越える is allowed. Currently such deinflection is disabled for all words; from my point of view we can either enable this deinflection for all ichidan verbs, or we need to add this kind of information to the JMDict.

**Comment by jimoow** [comment]
I note that JMDict has noun entries like 働き and 眠り but not 超え or 越え。So I think this bug can be closed  and I will ask JMDict maintainers, after I research a bit more. There must be a list somewhere...

**Comment by mvysny** [comment]
You can contact Jim Breen via mail, he's a very nice guy and easily approachable. The JMDict data files can be found here: http://www.edrdg.org/jmdict/edict_doc.html

Please let me know of the outcome of the conversation; if the JMDict format/data is changed, I'll need to add this fact to Aedict Indexer and Aedict itself.

I'll close this bug as won't fix (since it's not possible for Aedict to have necessary information right now), but please feel free to reopen when things change.
