### ISSUE TITLE
[Exact search] Example search has no results

### ISSUE THREAD

**Issue by Spanja** [mvysny/aedict#863]
Hello,

If I'm looking for examples that contains ごめん, I get no results.
But If I search ごめん, get the first entry (御免) and go to examples tab, there are plenty results

**Comment by mvysny** [comment]
Hi, thanks for letting me know! This works for me - please make sure that you have at least "Starts With" selected when you do the search.

**Comment by Spanja** [comment]
Yes, both example searches give none results
french dictionary, 3.50.10

![screenshot_20190220-182431](https://user-images.githubusercontent.com/626863/53080973-3598e300-353d-11e9-8319-fc2436a670a1.png)

**Comment by mvysny** [comment]
Yes, that's because there is no exact sentence reading just "ごめん". You need to at least select the 本.. radio button, to find sentences that Start With ごめん.

**Comment by Spanja** [comment]
Ok Indeed that's working.
But I don't understand, why are there results if i'm searching 食べる with the same settings and none with ごめん ?
There are no exact sentences with just 食べる

**Comment by mvysny** [comment]
That's a good question. Let me investigate.

**Comment by Spanja** [comment]
I don't know if that's linked to this exact search problem, but when I search 吸う (すう, to smoke), I get some extra results :
![screenshot_20190221-072335](https://user-images.githubusercontent.com/626863/53137853-abe22780-35c7-11e9-8453-1701246ad9e3.png)

**Comment by mvysny** [comment]
Yes, that's the current limitation of the search technology I'm using. Yet
let me see what I can do.

**Comment by mvysny** [comment]
Could you please open a new bug.report for this?

**Comment by Spanja** [comment]
Sure !

**Comment by mvysny** [comment]
The "gomen" part of the bug didn't match since Tatoeba sentence doesn't contain reading for 間違 (gomen) - instead gomen was always present as "間違". Also, previously the whole sentence would have to match the input query exactly, but that doesn't make sense: with Exact I'm searching for exact words, not an exact sentence after all.
Fixed in Aedict 3.50.11 + new dictionary data files. The new data files will be released shortly, please make sure to update your dictionaries. I'll also release new Aedict shortly.
