### ISSUE TITLE
Reader: No way to close the persistent notification on android 9

### ISSUE THREAD

**Issue by Benhgift** [mvysny/aedict#869]
1. Pixel 2
2. Latest android 9 pie
3. https://i.imgur.com/qFnxSco.png
4. There isn't a way to close the persistent notification without resorting to "force closing" it. Most persistent apps have a "close" button on the dropdown which completely closes the app. **Clarification edit**: I want to close the entire app including notification. I'm not asking to keep the Reader running without the notification.

(PS I really love this app, it's extremely useful!)

**Comment by mvysny** [comment]
Unfortunately this is the limitation of Android 9 Pie. Starting from Android Pie, any app that starts a Foreground Service must show a Notification. For definition of Foreground vs Background service please see https://developer.android.com/guide/components/services . Currently Reader is Foreground since it needs to listen for clipboard events.

However, with Android 9 Pie you can stop the Reader service, and still be able to use Reader, since Reader integrates into Android 9 Copy menu. Simply launch Reader, go to the Settings and uncheck "Watch Clipboard" and "Always Available". Then, select any text anywhere in any other app - the menu should now show Aedict Reader.

Please let me know if this works for you.

**Comment by Benhgift** [comment]
@mvysny Sorry, I explained it poorly. I don't want it to keep running, background or foreground or otherwise. When I'm not actively doing anything japanese related I want to completely close the app. Currently I do this by long pressing the notification, clicking the information button, and clicking "force close", which isn't ideal at all.

Most apps (for example, my VPN service) allow me to completely close the app from a button on the persistent notification

**Comment by mvysny** [comment]
I see, thanks for the explanation! If I understand correctly, there should be a "close" button in the notification that would make Reader to completely stop all services and everything, remove the notification and kill itself? Makes sense to save memory and notification area space.

The disadvantage is that in order to relaunch Reader, you will need to run it via the launcher icon, since the notification will be gone.

**Comment by Benhgift** [comment]
Yes exactly right, we're on the same page now :)

As for the disadvantage, I don't think that's really a disadvantage, any persistent app that I've used is like that. Going back to my vpn app (nordvpn) example, after I tap "close" on the notification I do have to relaunch it from the app icon next time. My ssh app (termux) behaves that way too.

**Comment by mvysny** [comment]
Fixed in Reader 1.4.6

**Comment by Benhgift** [comment]
@mvysny I just updated and that's perfect! Thank you!

This made my day and I really appreciate it 😄

**Comment by mvysny** [comment]
Awesome, happy to hear that! :)
