### ISSUE TITLE
[FEATURE REQUEST] Japanese translation in romaji

### ISSUE THREAD

**Issue by malek78i** [mvysny/aedict#876]
Hello again. I "miss" a feature in Aedict3 that is in most other japanese dictionaries. Its "Japanese words in romaji". Examples:
ひらがな (romaji: hiragana)
ラーメン (romaji: ramen)
私は (romaji: watashi ha)

Is it already implemented?

Thank you!

**Comment by malek78i** [comment]
Sorry. I did not see it in the settings 😄

**Comment by mvysny** [comment]
No problem :) It looks that you successfully moved through your SD Card problem - how did you manage that please? :)

**Comment by malek78i** [comment]
I found out that there are two options of saving downloads: SD CARD OR INTERNAL MEMORY.
So, I choose "Internal Memory". I downloaded the files and went to the App section of my phone where I found the ~100 MB big Aedict App. Then I modded the App with "ApkEditor" and modificate the app's information (name, package name, version code, ...) to set the installation locate to "Prefer External". After Installing the modded version, the app has been installed to my SD-Card. I try downloading files again and the dictionary files are now on my SD-Card👌👌

**Comment by mvysny** [comment]
This is important piece of information, thank you for sharing! I'll link the SD-Card issue with this one, so that others can also use your solution.

However, there is no reason for Aedict to prevent being installed on the SD Card. I have added the `android:installLocation="auto"` attribute into the manifest (will be present in Aedict 3.50.16) as per https://developer.android.com/guide/topics/manifest/manifest-element.html#install ; since there is nothing that prevents me to do so. According to https://developer.android.com/guide/topics/data/install-location.html there are topics that needs to be taken into consideration:
* Services: does not really apply since Aedict only has short-lived services (when downloading dictionaries)
* Alarm Services: yeah the word-of-the-day will probably stop changing after you reinsert the SD-Card
* IME: does not apply since Aedict is not an IME
* No live wallpapers
* Aedict provides no widgets
* Aedict provides no Account Managers
* Aedict doesn't use Android's sync adapter but uses its own
* Aedict doesn't listen for boot-completed

**Comment by malek78i** [comment]
Okay! I'm glad to help!
This app is really amazing!
