### ISSUE TITLE
Broken link for frequency ranking explanation

### ISSUE THREAD

**Issue by Fandekasp** [mvysny/aedict#883]
Related: #539 

The link in the info popup is broken
http://www17408ui.sakura.ne.jp/tatsum/English_top_Tatsu.html

![Screenshot_20190817-110026](https://user-images.githubusercontent.com/260983/63205372-6158e800-c0de-11e9-9047-cacaf4c27a13.png)

**Comment by mvysny** [comment]
Thank you, you're right - the page is not available anymore and is giving 404 NOT FOUND.

I am unfortunately unable to find a new link which explains the Matsushita occurrence index. Here is a list of links containing possible sources where we can find a correct link to the information:

* Aedict bug report #883 discussing the Matsushita Index
* I've found a PDF "In What Order Should Learners Learn Japanese Vocabulary? A Corpus-based Approach" by Tatsuhiko Matsushita, I'm attaching it to this bug so that it is preserved.

**Comment by mvysny** [comment]
[In What Order Should Learners Learn Japanese Vocabulary - Tatsuhiko Matsushita.pdf](https://github.com/mvysny/aedict/files/3511703/In.What.Order.Should.Learners.Learn.Japanese.Vocabulary.-.Tatsuhiko.Matsushita.pdf)

**Comment by mvysny** [comment]
* Luckily Internet Archive contains an archived version of the page: https://web.archive.org/web/20160422011816/http://www17408ui.sakura.ne.jp/tatsum/English_top_Tatsu.html - very flashy :-D I wonder if it is useful at all.

@Fandekasp could you please review the page whether it is any useful?

**Comment by Fandekasp** [comment]
@mvysny thanks for your work! Looking at the page, the only information that seems somewhat useful is

> This is a new vocabulary database created from a huge language data
called Balanced Corpus of Contemporary Written Japanese 2009 monitor version  (NINJAL, 2009) which are sampled texts from many books and internet forum sites.
The database contains approximately 20000 words ranked by importance (usage coefficient: product of frequency and dispersion).

Maybe we don't need an external link, and a succinct description could suffice :smile:

**Comment by mvysny** [comment]
What about I change the text to what you suggested, plus I'll fix the link to point this issue? Then the interested reader can find all the information he needs from this thread, including the PDF.

**Comment by mvysny** [comment]
Fixed in 3.50.16.

**Comment by TMHood** [comment]
Try here: http://www17408ui.sakura.ne.jp/tatsum/database.html
