### ISSUE TITLE
Show pitch accent on first search results screen

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#893]
It would be cool if the pitch accent were shown with underbar, overbar, and downstep arrow on the first search results screen (blue text in first screenshot), just like it is currently shown on the vocabulary detail screen (second screenshot).
![Screenshot_20191018-000857](https://user-images.githubusercontent.com/2184268/67092654-ccc24300-f17d-11e9-80a9-81139c8c0a11.png)
![Screenshot_20191018-000904](https://user-images.githubusercontent.com/2184268/67092672-db105f00-f17d-11e9-85da-27ab073a6cba.png)

**Comment by mvysny** [comment]
Sounds good, thank you, let me try to implement this.

**Comment by mvysny** [comment]
Thank you. I think that by default it's good not to show the pitch accent in the list, to not to overwhelm the user. I've added a new configuration option to Settings / GUi Tuning / Dictionary Entry Screen / Show Pitch Accent in Entry Lists, just make sure it's checked and you should now see the pitch accent in all lists.

Fixed in Aedict 3.50.17

**Comment by mvysny** [comment]
Damn, the pitch character messes up the blueish highlight selection and turns it off for entries with pitch characters... I'll have to deal with this in a separate issue.
