### ISSUE TITLE
[REQUEST] Aedict based Arabic dictionary

### ISSUE THREAD

**Issue by malekairmaroc7** [mvysny/aedict#903]
Hey (again XD)

May I ask if you are able to create an Aedict App but with Arabic — English dictionary like the Japanese one?

Thank you in advance for a reply :D!

**Comment by mvysny** [comment]
Hello, thank you for asking :) Hmm, that's a very intriguing question :)

1. Unfortunately I have no knowledge/understanding of the Arabic language: the grammar, how the alphabet system works, etc. Such knowledge is required if a proper support for e.g. verb deinflection is to be made.
2. Very few users are willing to pay for such a dictionary (lesson learned from Aedict), so it's usually not financially sound to create such a dictionary (unless it's a hobby project).
3. I'm not sure whether there is a dictionary file in plaintext I could index.
4. I have done no such research, but I would expect that there are high-quality Arabic dictionary apps already present in the Google Play. If yes, I wonder if there is much sense to compete against those dictionaries.
5. Unfortunately my kids+wife and my demanding work leaves me no spare time for such projects.

Because of the above, I'm leaning towards "not now".

**Comment by malekairmaroc7** [comment]
Alright. Thank you for answering :D!

**Comment by mvysny** [comment]
Sorry - Aedict UI is largely based on Japanese glyphs; porting the app to Arabic is not possible without a complete rewrite.
