### ISSUE TITLE
Translations in example sentences are not wrapped

### ISSUE THREAD

**Issue by mjaj** [mvysny/aedict#928]
Hello Martin,
I just ran into a minor display issue (I assume it is not intended this way):
On my tablet running Android 8.1.0, when searching within examples, long lines of the Japanese example sentences are correctly wrapped, however not the translations.
![Screenshot_20200911-102458_Aedict](https://user-images.githubusercontent.com/15126895/92896405-a0aa5300-f41c-11ea-973d-36a4f6346e86.jpg)
After selecting an entry, it is correctly displayed on the next screen, together with the analysis.
This issue is rarely seen, as the example sentence must be rather long; however it happens a bit more frequently when the GUI option "Show entry previews" is active.

**Comment by mvysny** [comment]
Thank you! Fixed in Aedict 3.50.20.

Initially the ellipsis was used because the Daijirin dictionary provides very lengthy dictionary-class explanations, which would utterly clutter the result screen. However, Tatoeba provides example sentences with sane length, and therefore it wouldn't hurt enable multiline for example sentences.
