### ISSUE TITLE
Failed to create Aedict dictionary on SD card

### ISSUE THREAD

**Issue by Sauhund** [mvysny/aedict#931]
1. Your phone brand and maker
Huawei P30

2. The exact Android version.
EMUI 10.1.0
Android 10

3. A screenshot if possible; even better, a youtube video demonstrating the issue.
See screenshot. 

4. A full description of the issue you're experiencing.
![Screenshot_20201010_180312_sk baka aedict3](https://user-images.githubusercontent.com/72664953/95660539-dda35b80-0b28-11eb-8c55-388f0ac2d942.jpg)

Aedict keeps reminding on every app start, that it "failed to create Aedict dictionary on SD card", although dictionaries are already downloaded to internal storage. This notification also hides the keyboard for several seconds. 
See screenshot.

**Comment by mvysny** [comment]
Hi, Android 10 unfortunately severely limited apps to access the SD Card, even if the app asks for the access to the SD Card. Did you install Aedict on a phone that already had Android 10, or have you upgraded to Android 10 after Aedict has been installed on your phone please? If the latter one, reinstalling Aedict or nuking+redownloading dictionaries could help, since Android 10 most likely now reports a different best location on a SD Card to store things. Beware though: uninstalling Aedict will wipe your Aedict-related data unless you store them on Aedict Online.

**Comment by Sauhund** [comment]
Hi, thanks for the feedback. The message still appears. 

I have nuked and reinstalled Aedict. Upon initial configuration, I chose internal memory.
![Screenshot_20201012_094217](https://user-images.githubusercontent.com/72664953/95718894-5ca2ac00-0c6f-11eb-9110-0462852e7460.jpg)

**Comment by Sauhund** [comment]
Hi there,
will there be any workaround for this soon?

**Comment by mvysny** [comment]
Unfortunately I would need to have access to your phone to fix that, which is not possible. "Thanks" to Android fragmentation and thousands of environments and Android versions, it's impossible to fix issues such as these. You need to find a writable folder for Aedict. Try reinstalling Aedict from scratch, maybe enabling read+write access for Aedict to SD Card in your phone's settings / app settings; enable all permissions for Aedict; try to google around for similar issues for your phone.

I suspect that the issue started after your phone upgraded to newer Android; or alternatively the issue appeared after Aedict has been updated to a newer version, since I have had to target Aedict to Android API 29 (Google rules).

Aedict will by default ask Android for a writable space in your phone, I have no clue why this request is apparently denied by Android.

Try pressing the "Use Internal Memory" button - that should use the most compatible path.

**Comment by mvysny** [comment]
It sounds like you have swapped the SD Card with Aedict dictionaries into the new phone with Android 10. Unfortunately Android will not allow Aedict to access SD Card anymore on Android 10+, you need to re-download the dictionaries into the internal memory.

**Comment by Sauhund** [comment]
Sorry, as I mentioned before, there is no SD card at all in the new phone P30. I already did nuke, uninstall and reinstall. Nothing of it worked. Is it not possible to just hide the notification or at least make it appear for less than those unnecessarily long 4 seconds?

**Comment by andzzzzz** [comment]
I have the very same problem here on my Sony Xperia 1 II.

**Comment by mvysny** [comment]
Let me investigate - there are multiple storages available for android (internal/external), perhaps I'm not using the proper one.

**Comment by Sauhund** [comment]
Thanks in advance!
I noticed another issue which could be related. 
When trying to export my notepad as CSV (Save to disk), I'm getting an error message as well. 
![Screenshot_20201121_085612](https://user-images.githubusercontent.com/72664953/99871037-ca7bb500-2bd7-11eb-8893-9138079135d1.jpg)

**Comment by mvysny** [comment]
Could you please file that bug as a separate one?

**Comment by Sauhund** [comment]
Done.

**Comment by andzzzzz** [comment]
Thank you very much too, but I think issue #940 and #941 are the same as I have this one and #940. Almost the same as #941 from @Sauhund  .

**Comment by Laurence02** [comment]
I've got the same problem on the Realme 7 Pro, running Android 10. I do have an SD card, but I explicitly chose to install the dictionaries to the internal memory during the setup. I get the same toast error message during startup, although the app does not crash and the dictionaries work fine. It has also persisted through a couple reinstalls.

**Comment by kuro68k** [comment]
I have the same issue on a Google Pixel 5 running Android 11. Similar to Laurence02, the app seems to work okay and does not crash. I have not extensively tested all functions however.

I am a software developer and would be happy to help if I can. I can use ADB.

**Comment by Sauhund** [comment]
Hi there, just wanted to add, this is more than just a cosmetic issue.
I have no possibility to export my notepad from Aedict, therefore the whole notepad feature is actually useless for me, as upon phone swap or maintenance cleanup, all my notes are completely lost.
It is quite a pity that there is no update on such an essential function.

**Comment by mvysny** [comment]
@kuro68k thank you kindly, that would be an awesome help! Could you obtain the Aedict- and SD Card-related logs from your phone and send them to me via e-mail? I'll take a look asap - it could be that it's only the Aedict sd card checker who's broken.

**Comment by mvysny** [comment]
@kuro68k gotcha, thank you. Thanks to the logs I've realized that the old FileStorage stubbornly tried to create the data files in an old location which is no longer available on modern Androids. I'll keep the class around for compatibility reason, but I'll create the files in Aedict-private folder.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.21.

**Comment by Sauhund** [comment]
Thanks! Is Aedict 3.50.21 on Playstore already? I don't have it available yet.

**Comment by mvysny** [comment]
Not yet, I'd like to fix a bunch of other tickets before releasing new version.
