### ISSUE TITLE
Inflection search with ~なければ form

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#947]
Hi Martin,

The search can detect the ~なければ form (`Base 1 + nakereba : if I do not do something` is displayed) but the search result doesn't display the correct entry

<img src="https://user-images.githubusercontent.com/626863/106077780-85cf4580-6155-11eb-82b5-a5a333c4d90c.jpg" width="300">

Same problem if I search `言わなければなりません` whereas this inflection is present in the verb inflections.

**Comment by mvysny** [comment]
Hmm, weird - the deinflection engine deinflected iwanakereba to iwanai but then stops there for some reason and doesn't deinflect iwanai to iu for some reason. Since iwanai is not present in JMDict, Aedict thinks it's a sentence and performs sentence analysis on it, which in this case is a step in a completely wrong direction :-D

**Comment by mvysny** [comment]
It could be that there is a bug in the deinflection engine. Would you like to take a shot on fixing it yourself? If yes, just send me a mail at martin@vysny.me and I'll give you access to the sources of the deinflection library.

**Comment by mvysny** [comment]
Excellent work fixing the deinflector @rbleuse at https://gitlab.com/mvysny/jputils/-/merge_requests/1 - thank you so much. I've released jputils 2.0 to Maven Central and v-bumped it in Aedict, which should solve this issue.

Fixed in Aedict 3.50.21.
