### ISSUE TITLE
SD Card "Warning" pop up

### ISSUE THREAD

**Issue by malekairmaroc7** [mvysny/aedict#957]
Hey!

It's been a while since I reported something here ;). Anyways, I get a popup whenever I start Aedict saying that it couldn't write data to the SD Card and will cause the app to crash (which didn't happen though... yet). Is that a bug?
(Redmi 9A - Android 10 / MIUI 12)

![Screenshot_2021-05-15-22-08-44-611_sk baka aedict3](https://user-images.githubusercontent.com/17984577/118377036-c8654280-b5cb-11eb-99a2-1b1e9886a18e.jpg)

**Comment by mvysny** [comment]
Welcome back :wave:  ;) Hmm intriguing, let me take a look.

**Comment by dadav** [comment]
#931?

**Comment by mvysny** [comment]
Yup, thanks, #931 is definitely related.
* If you're using the new UMN storage (default), you can safely ignore this error - it stores the database files into completely different directory.
* If you're using the old "File" storage (which you definitely shouldn't - it's slow and memory-demanding), then this bug may prevent you from storing custom stuff like Notepad, SRS etc.

You can check the storage type in Settings / Expert / Storage Type.

The old File storage used to store stuff on the SD Card. Unfortunately there are gazillion phones, storing stuff in myriad ways, and so it's not possible to implement a single working solution. Aedict tries to guess the best location, then create a folder there and hope for the best. And sometimes the folder can't be created because of SD Card access restrictions (even though Aedict should have write access to the SD Card)... Complete crazyness, see https://github.com/mvysny/aedict/issues?q=is%3Aissue+sdcard for more details.

The old storage type has been deprecated for a couple of years already (3+ years), but I'm still hesitant to remove it :-D I'll however disable the error message:
* If anyone is using the old File storage then it apparently works for them and the error notification is useless.
* For anyone using the UMN storage the notification is completely useless anyway.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.21
